package com.rydr.mapper;

import com.rydr.dto.valuation.discount.DiscountCondition;
import com.rydr.dto.valuation.discount.DiscountPrice;
import com.rydr.entity.DynamicDiscountRule;

public interface DynamicDiscountRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dynamic_discount_rule
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dynamic_discount_rule
     *
     * @mbggenerated
     */
    int insert(DynamicDiscountRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dynamic_discount_rule
     *
     * @mbggenerated
     */
    int insertSelective(DynamicDiscountRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dynamic_discount_rule
     *
     * @mbggenerated
     */
    DynamicDiscountRule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dynamic_discount_rule
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DynamicDiscountRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dynamic_discount_rule
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DynamicDiscountRule record);

    /**
     * This method corresponds to the database table tbl_dynamic_discount_rule
     */
    DiscountPrice findDiscountByCondition(DiscountCondition condition);
}