package com.online.taxi.mapper;

import com.online.taxi.entity.OrderRulePriceDetail;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OrderRulePriceDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_rule_price_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_rule_price_detail
     *
     * @mbggenerated
     */
    int insert(OrderRulePriceDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_rule_price_detail
     *
     * @mbggenerated
     */
    int insertSelective(OrderRulePriceDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_rule_price_detail
     *
     * @mbggenerated
     */
    OrderRulePriceDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_rule_price_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrderRulePriceDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_rule_price_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderRulePriceDetail record);

    /**
     * This method corresponds to the database table tbl_order_rule_price_detail
     */
    int insertList(List<OrderRulePriceDetail> records);

    /**
     * This method corresponds to the database table tbl_order_rule_price_detail
     */
    int deleteByOrderIdAndCategory(@Param("orderId") int orderId, @Param("category") Integer category);
}
