package com.online.taxi.mapper;

import com.online.taxi.entity.OrderRulePrice;
import org.apache.ibatis.annotations.Param;

public interface OrderRulePriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_rule_price
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_rule_price
     *
     * @mbggenerated
     */
    int insert(OrderRulePrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_rule_price
     *
     * @mbggenerated
     */
    int insertSelective(OrderRulePrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_rule_price
     *
     * @mbggenerated
     */
    OrderRulePrice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_rule_price
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrderRulePrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_rule_price
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderRulePrice record);

    /**
     * This method corresponds to the database table tbl_order_rule_price
     */
    int deleteByOrderIdAndCategory(@Param("orderId") int orderId, @Param("category") Integer category);
}
