package com.online.taxi.entity;

import java.util.Date;

public class BaseInfoCompanyService {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_base_info_company_service.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_base_info_company_service.service_name
     *
     * @mbggenerated
     */
    private String serviceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_base_info_company_service.service_no
     *
     * @mbggenerated
     */
    private String serviceNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_base_info_company_service.detail_address
     *
     * @mbggenerated
     */
    private String detailAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_base_info_company_service.responsible_name
     *
     * @mbggenerated
     */
    private String responsibleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_base_info_company_service.responsible_phone
     *
     * @mbggenerated
     */
    private String responsiblePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_base_info_company_service.manager_name
     *
     * @mbggenerated
     */
    private String managerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_base_info_company_service.manager_phone
     *
     * @mbggenerated
     */
    private String managerPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_base_info_company_service.contact_phone
     *
     * @mbggenerated
     */
    private String contactPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_base_info_company_service.mail_address
     *
     * @mbggenerated
     */
    private String mailAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_base_info_company_service.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_base_info_company_service.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_base_info_company_service.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_base_info_company_service.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_base_info_company_service.id
     *
     * @return the value of tbl_base_info_company_service.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_base_info_company_service.id
     *
     * @param id the value for tbl_base_info_company_service.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_base_info_company_service.service_name
     *
     * @return the value of tbl_base_info_company_service.service_name
     *
     * @mbggenerated
     */
    public String getServiceName() {
        return serviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_base_info_company_service.service_name
     *
     * @param serviceName the value for tbl_base_info_company_service.service_name
     *
     * @mbggenerated
     */
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName == null ? null : serviceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_base_info_company_service.service_no
     *
     * @return the value of tbl_base_info_company_service.service_no
     *
     * @mbggenerated
     */
    public String getServiceNo() {
        return serviceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_base_info_company_service.service_no
     *
     * @param serviceNo the value for tbl_base_info_company_service.service_no
     *
     * @mbggenerated
     */
    public void setServiceNo(String serviceNo) {
        this.serviceNo = serviceNo == null ? null : serviceNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_base_info_company_service.detail_address
     *
     * @return the value of tbl_base_info_company_service.detail_address
     *
     * @mbggenerated
     */
    public String getDetailAddress() {
        return detailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_base_info_company_service.detail_address
     *
     * @param detailAddress the value for tbl_base_info_company_service.detail_address
     *
     * @mbggenerated
     */
    public void setDetailAddress(String detailAddress) {
        this.detailAddress = detailAddress == null ? null : detailAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_base_info_company_service.responsible_name
     *
     * @return the value of tbl_base_info_company_service.responsible_name
     *
     * @mbggenerated
     */
    public String getResponsibleName() {
        return responsibleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_base_info_company_service.responsible_name
     *
     * @param responsibleName the value for tbl_base_info_company_service.responsible_name
     *
     * @mbggenerated
     */
    public void setResponsibleName(String responsibleName) {
        this.responsibleName = responsibleName == null ? null : responsibleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_base_info_company_service.responsible_phone
     *
     * @return the value of tbl_base_info_company_service.responsible_phone
     *
     * @mbggenerated
     */
    public String getResponsiblePhone() {
        return responsiblePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_base_info_company_service.responsible_phone
     *
     * @param responsiblePhone the value for tbl_base_info_company_service.responsible_phone
     *
     * @mbggenerated
     */
    public void setResponsiblePhone(String responsiblePhone) {
        this.responsiblePhone = responsiblePhone == null ? null : responsiblePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_base_info_company_service.manager_name
     *
     * @return the value of tbl_base_info_company_service.manager_name
     *
     * @mbggenerated
     */
    public String getManagerName() {
        return managerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_base_info_company_service.manager_name
     *
     * @param managerName the value for tbl_base_info_company_service.manager_name
     *
     * @mbggenerated
     */
    public void setManagerName(String managerName) {
        this.managerName = managerName == null ? null : managerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_base_info_company_service.manager_phone
     *
     * @return the value of tbl_base_info_company_service.manager_phone
     *
     * @mbggenerated
     */
    public String getManagerPhone() {
        return managerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_base_info_company_service.manager_phone
     *
     * @param managerPhone the value for tbl_base_info_company_service.manager_phone
     *
     * @mbggenerated
     */
    public void setManagerPhone(String managerPhone) {
        this.managerPhone = managerPhone == null ? null : managerPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_base_info_company_service.contact_phone
     *
     * @return the value of tbl_base_info_company_service.contact_phone
     *
     * @mbggenerated
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_base_info_company_service.contact_phone
     *
     * @param contactPhone the value for tbl_base_info_company_service.contact_phone
     *
     * @mbggenerated
     */
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone == null ? null : contactPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_base_info_company_service.mail_address
     *
     * @return the value of tbl_base_info_company_service.mail_address
     *
     * @mbggenerated
     */
    public String getMailAddress() {
        return mailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_base_info_company_service.mail_address
     *
     * @param mailAddress the value for tbl_base_info_company_service.mail_address
     *
     * @mbggenerated
     */
    public void setMailAddress(String mailAddress) {
        this.mailAddress = mailAddress == null ? null : mailAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_base_info_company_service.create_date
     *
     * @return the value of tbl_base_info_company_service.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_base_info_company_service.create_date
     *
     * @param createDate the value for tbl_base_info_company_service.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_base_info_company_service.state
     *
     * @return the value of tbl_base_info_company_service.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_base_info_company_service.state
     *
     * @param state the value for tbl_base_info_company_service.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_base_info_company_service.create_time
     *
     * @return the value of tbl_base_info_company_service.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_base_info_company_service.create_time
     *
     * @param createTime the value for tbl_base_info_company_service.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_base_info_company_service.update_time
     *
     * @return the value of tbl_base_info_company_service.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_base_info_company_service.update_time
     *
     * @param updateTime the value for tbl_base_info_company_service.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}