package com.online.taxi.entity;

import java.util.Date;

public class CarBaseInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_base_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_base_info.company_logo
     *
     * @mbggenerated
     */
    private String companyLogo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_base_info.car_label
     *
     * @mbggenerated
     */
    private String carLabel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_base_info.car_base_type
     *
     * @mbggenerated
     */
    private String carBaseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_base_info.car_owner
     *
     * @mbggenerated
     */
    private String carOwner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_base_info.plate_color
     *
     * @mbggenerated
     */
    private String plateColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_base_info.engine_number
     *
     * @mbggenerated
     */
    private String engineNumber;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_base_info.vin_number
     *
     * @mbggenerated
     */
    private String vinNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_base_info.register_time
     *
     * @mbggenerated
     */
    private Date registerTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_base_info.fuel_type
     *
     * @mbggenerated
     */
    private String fuelType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_base_info.engine_capacity
     *
     * @mbggenerated
     */
    private String engineCapacity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_base_info.car_img_file_number
     *
     * @mbggenerated
     */
    private String carImgFileNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_base_info.transport_number
     *
     * @mbggenerated
     */
    private String transportNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_base_info.transport_issuing_authority
     *
     * @mbggenerated
     */
    private String transportIssuingAuthority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_base_info.business_area
     *
     * @mbggenerated
     */
    private String businessArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_base_info.transport_certificate_validity_start
     *
     * @mbggenerated
     */
    private Date transportCertificateValidityStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_base_info.transport_certificate_validity_end
     *
     * @mbggenerated
     */
    private Date transportCertificateValidityEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_base_info.first_register_time
     *
     * @mbggenerated
     */
    private Date firstRegisterTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_base_info.state_of_repair
     *
     * @mbggenerated
     */
    private String stateOfRepair;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_base_info.next_annual_inspection_time
     *
     * @mbggenerated
     */
    private Date nextAnnualInspectionTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_base_info.annual_audit_status
     *
     * @mbggenerated
     */
    private String annualAuditStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_base_info.invoice_printing_equipment_number
     *
     * @mbggenerated
     */
    private String invoicePrintingEquipmentNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_base_info.gps_brand
     *
     * @mbggenerated
     */
    private String gpsBrand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_base_info.gps_model
     *
     * @mbggenerated
     */
    private String gpsModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_base_info.gps_imei
     *
     * @mbggenerated
     */
    private String gpsImei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_base_info.gps_install_time
     *
     * @mbggenerated
     */
    private Date gpsInstallTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_base_info.report_time
     *
     * @mbggenerated
     */
    private Date reportTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_base_info.service_type
     *
     * @mbggenerated
     */
    private String serviceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_base_info.charge_type_code
     *
     * @mbggenerated
     */
    private String chargeTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_base_info.car_invoice_img
     *
     * @mbggenerated
     */
    private String carInvoiceImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_base_info.quality_certificate_img
     *
     * @mbggenerated
     */
    private String qualityCertificateImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_base_info.vehicle_license_img
     *
     * @mbggenerated
     */
    private String vehicleLicenseImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_base_info.registration_certificate_img
     *
     * @mbggenerated
     */
    private String registrationCertificateImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_base_info.tax_payment_certificate_img
     *
     * @mbggenerated
     */
    private String taxPaymentCertificateImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_base_info.transport_certificate_img
     *
     * @mbggenerated
     */
    private String transportCertificateImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_base_info.other_img1
     *
     * @mbggenerated
     */
    private String otherImg1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_base_info.other_img2
     *
     * @mbggenerated
     */
    private String otherImg2;
    private Date createTime;
    private Date updateTime;

    public Date getCreateTime() {
        return createTime;
    }

    public CarBaseInfo setCreateTime(Date createTime) {
        this.createTime = createTime;
        return this;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public CarBaseInfo setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_base_info.id
     *
     * @return the value of tbl_car_base_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_base_info.id
     *
     * @param id the value for tbl_car_base_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_base_info.company_logo
     *
     * @return the value of tbl_car_base_info.company_logo
     *
     * @mbggenerated
     */
    public String getCompanyLogo() {
        return companyLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_base_info.company_logo
     *
     * @param companyLogo the value for tbl_car_base_info.company_logo
     *
     * @mbggenerated
     */
    public void setCompanyLogo(String companyLogo) {
        this.companyLogo = companyLogo == null ? null : companyLogo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_base_info.car_label
     *
     * @return the value of tbl_car_base_info.car_label
     *
     * @mbggenerated
     */
    public String getCarLabel() {
        return carLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_base_info.car_label
     *
     * @param carLabel the value for tbl_car_base_info.car_label
     *
     * @mbggenerated
     */
    public void setCarLabel(String carLabel) {
        this.carLabel = carLabel == null ? null : carLabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_base_info.car_base_type
     *
     * @return the value of tbl_car_base_info.car_base_type
     *
     * @mbggenerated
     */
    public String getCarBaseType() {
        return carBaseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_base_info.car_base_type
     *
     * @param carBaseType the value for tbl_car_base_info.car_base_type
     *
     * @mbggenerated
     */
    public void setCarBaseType(String carBaseType) {
        this.carBaseType = carBaseType == null ? null : carBaseType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_base_info.car_owner
     *
     * @return the value of tbl_car_base_info.car_owner
     *
     * @mbggenerated
     */
    public String getCarOwner() {
        return carOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_base_info.car_owner
     *
     * @param carOwner the value for tbl_car_base_info.car_owner
     *
     * @mbggenerated
     */
    public void setCarOwner(String carOwner) {
        this.carOwner = carOwner == null ? null : carOwner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_base_info.plate_color
     *
     * @return the value of tbl_car_base_info.plate_color
     *
     * @mbggenerated
     */
    public String getPlateColor() {
        return plateColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_base_info.plate_color
     *
     * @param plateColor the value for tbl_car_base_info.plate_color
     *
     * @mbggenerated
     */
    public void setPlateColor(String plateColor) {
        this.plateColor = plateColor == null ? null : plateColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_base_info.engine_number
     *
     * @return the value of tbl_car_base_info.engine_number
     *
     * @mbggenerated
     */
    public String getEngineNumber() {
        return engineNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_base_info.engine_number
     *
     * @param engineNumber the value for tbl_car_base_info.engine_number
     *
     * @mbggenerated
     */
    public void setEngineNumber(String engineNumber) {
        this.engineNumber = engineNumber == null ? null : engineNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_base_info.vin_number
     *
     * @return the value of tbl_car_base_info.vin_number
     *
     * @mbggenerated
     */
    public String getVinNumber() {
        return vinNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_base_info.vin_number
     *
     * @param vinNumber the value for tbl_car_base_info.vin_number
     *
     * @mbggenerated
     */
    public void setVinNumber(String vinNumber) {
        this.vinNumber = vinNumber == null ? null : vinNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_base_info.register_time
     *
     * @return the value of tbl_car_base_info.register_time
     *
     * @mbggenerated
     */
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_base_info.register_time
     *
     * @param registerTime the value for tbl_car_base_info.register_time
     *
     * @mbggenerated
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_base_info.fuel_type
     *
     * @return the value of tbl_car_base_info.fuel_type
     *
     * @mbggenerated
     */
    public String getFuelType() {
        return fuelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_base_info.fuel_type
     *
     * @param fuelType the value for tbl_car_base_info.fuel_type
     *
     * @mbggenerated
     */
    public void setFuelType(String fuelType) {
        this.fuelType = fuelType == null ? null : fuelType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_base_info.engine_capacity
     *
     * @return the value of tbl_car_base_info.engine_capacity
     *
     * @mbggenerated
     */
    public String getEngineCapacity() {
        return engineCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_base_info.engine_capacity
     *
     * @param engineCapacity the value for tbl_car_base_info.engine_capacity
     *
     * @mbggenerated
     */
    public void setEngineCapacity(String engineCapacity) {
        this.engineCapacity = engineCapacity == null ? null : engineCapacity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_base_info.car_img_file_number
     *
     * @return the value of tbl_car_base_info.car_img_file_number
     *
     * @mbggenerated
     */
    public String getCarImgFileNumber() {
        return carImgFileNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_base_info.car_img_file_number
     *
     * @param carImgFileNumber the value for tbl_car_base_info.car_img_file_number
     *
     * @mbggenerated
     */
    public void setCarImgFileNumber(String carImgFileNumber) {
        this.carImgFileNumber = carImgFileNumber == null ? null : carImgFileNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_base_info.transport_number
     *
     * @return the value of tbl_car_base_info.transport_number
     *
     * @mbggenerated
     */
    public String getTransportNumber() {
        return transportNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_base_info.transport_number
     *
     * @param transportNumber the value for tbl_car_base_info.transport_number
     *
     * @mbggenerated
     */
    public void setTransportNumber(String transportNumber) {
        this.transportNumber = transportNumber == null ? null : transportNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_base_info.transport_issuing_authority
     *
     * @return the value of tbl_car_base_info.transport_issuing_authority
     *
     * @mbggenerated
     */
    public String getTransportIssuingAuthority() {
        return transportIssuingAuthority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_base_info.transport_issuing_authority
     *
     * @param transportIssuingAuthority the value for tbl_car_base_info.transport_issuing_authority
     *
     * @mbggenerated
     */
    public void setTransportIssuingAuthority(String transportIssuingAuthority) {
        this.transportIssuingAuthority = transportIssuingAuthority == null ? null : transportIssuingAuthority.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_base_info.business_area
     *
     * @return the value of tbl_car_base_info.business_area
     *
     * @mbggenerated
     */
    public String getBusinessArea() {
        return businessArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_base_info.business_area
     *
     * @param businessArea the value for tbl_car_base_info.business_area
     *
     * @mbggenerated
     */
    public void setBusinessArea(String businessArea) {
        this.businessArea = businessArea == null ? null : businessArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_base_info.transport_certificate_validity_start
     *
     * @return the value of tbl_car_base_info.transport_certificate_validity_start
     *
     * @mbggenerated
     */
    public Date getTransportCertificateValidityStart() {
        return transportCertificateValidityStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_base_info.transport_certificate_validity_start
     *
     * @param transportCertificateValidityStart the value for tbl_car_base_info.transport_certificate_validity_start
     *
     * @mbggenerated
     */
    public void setTransportCertificateValidityStart(Date transportCertificateValidityStart) {
        this.transportCertificateValidityStart = transportCertificateValidityStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_base_info.transport_certificate_validity_end
     *
     * @return the value of tbl_car_base_info.transport_certificate_validity_end
     *
     * @mbggenerated
     */
    public Date getTransportCertificateValidityEnd() {
        return transportCertificateValidityEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_base_info.transport_certificate_validity_end
     *
     * @param transportCertificateValidityEnd the value for tbl_car_base_info.transport_certificate_validity_end
     *
     * @mbggenerated
     */
    public void setTransportCertificateValidityEnd(Date transportCertificateValidityEnd) {
        this.transportCertificateValidityEnd = transportCertificateValidityEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_base_info.first_register_time
     *
     * @return the value of tbl_car_base_info.first_register_time
     *
     * @mbggenerated
     */
    public Date getFirstRegisterTime() {
        return firstRegisterTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_base_info.first_register_time
     *
     * @param firstRegisterTime the value for tbl_car_base_info.first_register_time
     *
     * @mbggenerated
     */
    public void setFirstRegisterTime(Date firstRegisterTime) {
        this.firstRegisterTime = firstRegisterTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_base_info.state_of_repair
     *
     * @return the value of tbl_car_base_info.state_of_repair
     *
     * @mbggenerated
     */
    public String getStateOfRepair() {
        return stateOfRepair;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_base_info.state_of_repair
     *
     * @param stateOfRepair the value for tbl_car_base_info.state_of_repair
     *
     * @mbggenerated
     */
    public void setStateOfRepair(String stateOfRepair) {
        this.stateOfRepair = stateOfRepair == null ? null : stateOfRepair.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_base_info.next_annual_inspection_time
     *
     * @return the value of tbl_car_base_info.next_annual_inspection_time
     *
     * @mbggenerated
     */
    public Date getNextAnnualInspectionTime() {
        return nextAnnualInspectionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_base_info.next_annual_inspection_time
     *
     * @param nextAnnualInspectionTime the value for tbl_car_base_info.next_annual_inspection_time
     *
     * @mbggenerated
     */
    public void setNextAnnualInspectionTime(Date nextAnnualInspectionTime) {
        this.nextAnnualInspectionTime = nextAnnualInspectionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_base_info.annual_audit_status
     *
     * @return the value of tbl_car_base_info.annual_audit_status
     *
     * @mbggenerated
     */
    public String getAnnualAuditStatus() {
        return annualAuditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_base_info.annual_audit_status
     *
     * @param annualAuditStatus the value for tbl_car_base_info.annual_audit_status
     *
     * @mbggenerated
     */
    public void setAnnualAuditStatus(String annualAuditStatus) {
        this.annualAuditStatus = annualAuditStatus == null ? null : annualAuditStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_base_info.invoice_printing_equipment_number
     *
     * @return the value of tbl_car_base_info.invoice_printing_equipment_number
     *
     * @mbggenerated
     */
    public String getInvoicePrintingEquipmentNumber() {
        return invoicePrintingEquipmentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_base_info.invoice_printing_equipment_number
     *
     * @param invoicePrintingEquipmentNumber the value for tbl_car_base_info.invoice_printing_equipment_number
     *
     * @mbggenerated
     */
    public void setInvoicePrintingEquipmentNumber(String invoicePrintingEquipmentNumber) {
        this.invoicePrintingEquipmentNumber = invoicePrintingEquipmentNumber == null ? null : invoicePrintingEquipmentNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_base_info.gps_brand
     *
     * @return the value of tbl_car_base_info.gps_brand
     *
     * @mbggenerated
     */
    public String getGpsBrand() {
        return gpsBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_base_info.gps_brand
     *
     * @param gpsBrand the value for tbl_car_base_info.gps_brand
     *
     * @mbggenerated
     */
    public void setGpsBrand(String gpsBrand) {
        this.gpsBrand = gpsBrand == null ? null : gpsBrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_base_info.gps_model
     *
     * @return the value of tbl_car_base_info.gps_model
     *
     * @mbggenerated
     */
    public String getGpsModel() {
        return gpsModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_base_info.gps_model
     *
     * @param gpsModel the value for tbl_car_base_info.gps_model
     *
     * @mbggenerated
     */
    public void setGpsModel(String gpsModel) {
        this.gpsModel = gpsModel == null ? null : gpsModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_base_info.gps_imei
     *
     * @return the value of tbl_car_base_info.gps_imei
     *
     * @mbggenerated
     */
    public String getGpsImei() {
        return gpsImei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_base_info.gps_imei
     *
     * @param gpsImei the value for tbl_car_base_info.gps_imei
     *
     * @mbggenerated
     */
    public void setGpsImei(String gpsImei) {
        this.gpsImei = gpsImei == null ? null : gpsImei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_base_info.gps_install_time
     *
     * @return the value of tbl_car_base_info.gps_install_time
     *
     * @mbggenerated
     */
    public Date getGpsInstallTime() {
        return gpsInstallTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_base_info.gps_install_time
     *
     * @param gpsInstallTime the value for tbl_car_base_info.gps_install_time
     *
     * @mbggenerated
     */
    public void setGpsInstallTime(Date gpsInstallTime) {
        this.gpsInstallTime = gpsInstallTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_base_info.report_time
     *
     * @return the value of tbl_car_base_info.report_time
     *
     * @mbggenerated
     */
    public Date getReportTime() {
        return reportTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_base_info.report_time
     *
     * @param reportTime the value for tbl_car_base_info.report_time
     *
     * @mbggenerated
     */
    public void setReportTime(Date reportTime) {
        this.reportTime = reportTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_base_info.service_type
     *
     * @return the value of tbl_car_base_info.service_type
     *
     * @mbggenerated
     */
    public String getServiceType() {
        return serviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_base_info.service_type
     *
     * @param serviceType the value for tbl_car_base_info.service_type
     *
     * @mbggenerated
     */
    public void setServiceType(String serviceType) {
        this.serviceType = serviceType == null ? null : serviceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_base_info.charge_type_code
     *
     * @return the value of tbl_car_base_info.charge_type_code
     *
     * @mbggenerated
     */
    public String getChargeTypeCode() {
        return chargeTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_base_info.charge_type_code
     *
     * @param chargeTypeCode the value for tbl_car_base_info.charge_type_code
     *
     * @mbggenerated
     */
    public void setChargeTypeCode(String chargeTypeCode) {
        this.chargeTypeCode = chargeTypeCode == null ? null : chargeTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_base_info.car_invoice_img
     *
     * @return the value of tbl_car_base_info.car_invoice_img
     *
     * @mbggenerated
     */
    public String getCarInvoiceImg() {
        return carInvoiceImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_base_info.car_invoice_img
     *
     * @param carInvoiceImg the value for tbl_car_base_info.car_invoice_img
     *
     * @mbggenerated
     */
    public void setCarInvoiceImg(String carInvoiceImg) {
        this.carInvoiceImg = carInvoiceImg == null ? null : carInvoiceImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_base_info.quality_certificate_img
     *
     * @return the value of tbl_car_base_info.quality_certificate_img
     *
     * @mbggenerated
     */
    public String getQualityCertificateImg() {
        return qualityCertificateImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_base_info.quality_certificate_img
     *
     * @param qualityCertificateImg the value for tbl_car_base_info.quality_certificate_img
     *
     * @mbggenerated
     */
    public void setQualityCertificateImg(String qualityCertificateImg) {
        this.qualityCertificateImg = qualityCertificateImg == null ? null : qualityCertificateImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_base_info.vehicle_license_img
     *
     * @return the value of tbl_car_base_info.vehicle_license_img
     *
     * @mbggenerated
     */
    public String getVehicleLicenseImg() {
        return vehicleLicenseImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_base_info.vehicle_license_img
     *
     * @param vehicleLicenseImg the value for tbl_car_base_info.vehicle_license_img
     *
     * @mbggenerated
     */
    public void setVehicleLicenseImg(String vehicleLicenseImg) {
        this.vehicleLicenseImg = vehicleLicenseImg == null ? null : vehicleLicenseImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_base_info.registration_certificate_img
     *
     * @return the value of tbl_car_base_info.registration_certificate_img
     *
     * @mbggenerated
     */
    public String getRegistrationCertificateImg() {
        return registrationCertificateImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_base_info.registration_certificate_img
     *
     * @param registrationCertificateImg the value for tbl_car_base_info.registration_certificate_img
     *
     * @mbggenerated
     */
    public void setRegistrationCertificateImg(String registrationCertificateImg) {
        this.registrationCertificateImg = registrationCertificateImg == null ? null : registrationCertificateImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_base_info.tax_payment_certificate_img
     *
     * @return the value of tbl_car_base_info.tax_payment_certificate_img
     *
     * @mbggenerated
     */
    public String getTaxPaymentCertificateImg() {
        return taxPaymentCertificateImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_base_info.tax_payment_certificate_img
     *
     * @param taxPaymentCertificateImg the value for tbl_car_base_info.tax_payment_certificate_img
     *
     * @mbggenerated
     */
    public void setTaxPaymentCertificateImg(String taxPaymentCertificateImg) {
        this.taxPaymentCertificateImg = taxPaymentCertificateImg == null ? null : taxPaymentCertificateImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_base_info.transport_certificate_img
     *
     * @return the value of tbl_car_base_info.transport_certificate_img
     *
     * @mbggenerated
     */
    public String getTransportCertificateImg() {
        return transportCertificateImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_base_info.transport_certificate_img
     *
     * @param transportCertificateImg the value for tbl_car_base_info.transport_certificate_img
     *
     * @mbggenerated
     */
    public void setTransportCertificateImg(String transportCertificateImg) {
        this.transportCertificateImg = transportCertificateImg == null ? null : transportCertificateImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_base_info.other_img1
     *
     * @return the value of tbl_car_base_info.other_img1
     *
     * @mbggenerated
     */
    public String getOtherImg1() {
        return otherImg1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_base_info.other_img1
     *
     * @param otherImg1 the value for tbl_car_base_info.other_img1
     *
     * @mbggenerated
     */
    public void setOtherImg1(String otherImg1) {
        this.otherImg1 = otherImg1 == null ? null : otherImg1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_base_info.other_img2
     *
     * @return the value of tbl_car_base_info.other_img2
     *
     * @mbggenerated
     */
    public String getOtherImg2() {
        return otherImg2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_base_info.other_img2
     *
     * @param otherImg2 the value for tbl_car_base_info.other_img2
     *
     * @mbggenerated
     */
    public void setOtherImg2(String otherImg2) {
        this.otherImg2 = otherImg2 == null ? null : otherImg2.trim();
    }
}
