package com.online.taxi.entity;

import java.util.Date;

public class CarDispatchCapacitySet {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_dispatch_capacity_set.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_dispatch_capacity_set.city_code
     *
     * @mbggenerated
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_dispatch_capacity_set.car_service_period
     *
     * @mbggenerated
     */
    private String carServicePeriod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_dispatch_capacity_set.spare_driver_count
     *
     * @mbggenerated
     */
    private Integer spareDriverCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_dispatch_capacity_set.operator_id
     *
     * @mbggenerated
     */
    private Integer operatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_dispatch_capacity_set.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_dispatch_capacity_set.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_dispatch_capacity_set.id
     *
     * @return the value of tbl_car_dispatch_capacity_set.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_dispatch_capacity_set.id
     *
     * @param id the value for tbl_car_dispatch_capacity_set.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_dispatch_capacity_set.city_code
     *
     * @return the value of tbl_car_dispatch_capacity_set.city_code
     *
     * @mbggenerated
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_dispatch_capacity_set.city_code
     *
     * @param cityCode the value for tbl_car_dispatch_capacity_set.city_code
     *
     * @mbggenerated
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_dispatch_capacity_set.car_service_period
     *
     * @return the value of tbl_car_dispatch_capacity_set.car_service_period
     *
     * @mbggenerated
     */
    public String getCarServicePeriod() {
        return carServicePeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_dispatch_capacity_set.car_service_period
     *
     * @param carServicePeriod the value for tbl_car_dispatch_capacity_set.car_service_period
     *
     * @mbggenerated
     */
    public void setCarServicePeriod(String carServicePeriod) {
        this.carServicePeriod = carServicePeriod == null ? null : carServicePeriod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_dispatch_capacity_set.spare_driver_count
     *
     * @return the value of tbl_car_dispatch_capacity_set.spare_driver_count
     *
     * @mbggenerated
     */
    public Integer getSpareDriverCount() {
        return spareDriverCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_dispatch_capacity_set.spare_driver_count
     *
     * @param spareDriverCount the value for tbl_car_dispatch_capacity_set.spare_driver_count
     *
     * @mbggenerated
     */
    public void setSpareDriverCount(Integer spareDriverCount) {
        this.spareDriverCount = spareDriverCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_dispatch_capacity_set.operator_id
     *
     * @return the value of tbl_car_dispatch_capacity_set.operator_id
     *
     * @mbggenerated
     */
    public Integer getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_dispatch_capacity_set.operator_id
     *
     * @param operatorId the value for tbl_car_dispatch_capacity_set.operator_id
     *
     * @mbggenerated
     */
    public void setOperatorId(Integer operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_dispatch_capacity_set.create_time
     *
     * @return the value of tbl_car_dispatch_capacity_set.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_dispatch_capacity_set.create_time
     *
     * @param createTime the value for tbl_car_dispatch_capacity_set.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_dispatch_capacity_set.update_time
     *
     * @return the value of tbl_car_dispatch_capacity_set.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_dispatch_capacity_set.update_time
     *
     * @param updateTime the value for tbl_car_dispatch_capacity_set.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}