package com.online.taxi.entity;

import java.util.Date;

public class CarInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_info.plate_number
     *
     * @mbggenerated
     */
    private String plateNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_info.operation_status
     *
     * @mbggenerated
     */
    private Integer operationStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_info.publish_time
     *
     * @mbggenerated
     */
    private Date publishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_info.full_name
     *
     * @mbggenerated
     */
    private String fullName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_info.color
     *
     * @mbggenerated
     */
    private String color;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_info.car_img
     *
     * @mbggenerated
     */
    private String carImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_info.city_code
     *
     * @mbggenerated
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_info.car_type_id
     *
     * @mbggenerated
     */
    private Integer carTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_info.car_level_id
     *
     * @mbggenerated
     */
    private Integer carLevelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_info.regist_date
     *
     * @mbggenerated
     */
    private Date registDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_info.insurance_start_date
     *
     * @mbggenerated
     */
    private Date insuranceStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_info.insurance_end_date
     *
     * @mbggenerated
     */
    private Date insuranceEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_info.annual_end_date
     *
     * @mbggenerated
     */
    private Date annualEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_info.car_license_img
     *
     * @mbggenerated
     */
    private String carLicenseImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_info.is_free_order
     *
     * @mbggenerated
     */
    private Integer isFreeOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_info.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_info.use_status
     *
     * @mbggenerated
     */
    private Integer useStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_info.large_screen_device_code
     *
     * @mbggenerated
     */
    private String largeScreenDeviceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_info.large_screen_device_brand
     *
     * @mbggenerated
     */
    private String largeScreenDeviceBrand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_info.car_screen_device_code
     *
     * @mbggenerated
     */
    private String carScreenDeviceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_info.car_screen_device_brand
     *
     * @mbggenerated
     */
    private String carScreenDeviceBrand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_info.operator_id
     *
     * @mbggenerated
     */
    private Integer operatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_info.total_mile
     *
     * @mbggenerated
     */
    private Integer totalMile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_info.asset_coding
     *
     * @mbggenerated
     */
    private String assetCoding;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_info.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_info.id
     *
     * @return the value of tbl_car_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_info.id
     *
     * @param id the value for tbl_car_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_info.plate_number
     *
     * @return the value of tbl_car_info.plate_number
     *
     * @mbggenerated
     */
    public String getPlateNumber() {
        return plateNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_info.plate_number
     *
     * @param plateNumber the value for tbl_car_info.plate_number
     *
     * @mbggenerated
     */
    public void setPlateNumber(String plateNumber) {
        this.plateNumber = plateNumber == null ? null : plateNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_info.operation_status
     *
     * @return the value of tbl_car_info.operation_status
     *
     * @mbggenerated
     */
    public Integer getOperationStatus() {
        return operationStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_info.operation_status
     *
     * @param operationStatus the value for tbl_car_info.operation_status
     *
     * @mbggenerated
     */
    public void setOperationStatus(Integer operationStatus) {
        this.operationStatus = operationStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_info.publish_time
     *
     * @return the value of tbl_car_info.publish_time
     *
     * @mbggenerated
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_info.publish_time
     *
     * @param publishTime the value for tbl_car_info.publish_time
     *
     * @mbggenerated
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_info.full_name
     *
     * @return the value of tbl_car_info.full_name
     *
     * @mbggenerated
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_info.full_name
     *
     * @param fullName the value for tbl_car_info.full_name
     *
     * @mbggenerated
     */
    public void setFullName(String fullName) {
        this.fullName = fullName == null ? null : fullName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_info.color
     *
     * @return the value of tbl_car_info.color
     *
     * @mbggenerated
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_info.color
     *
     * @param color the value for tbl_car_info.color
     *
     * @mbggenerated
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_info.car_img
     *
     * @return the value of tbl_car_info.car_img
     *
     * @mbggenerated
     */
    public String getCarImg() {
        return carImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_info.car_img
     *
     * @param carImg the value for tbl_car_info.car_img
     *
     * @mbggenerated
     */
    public void setCarImg(String carImg) {
        this.carImg = carImg == null ? null : carImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_info.city_code
     *
     * @return the value of tbl_car_info.city_code
     *
     * @mbggenerated
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_info.city_code
     *
     * @param cityCode the value for tbl_car_info.city_code
     *
     * @mbggenerated
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_info.car_type_id
     *
     * @return the value of tbl_car_info.car_type_id
     *
     * @mbggenerated
     */
    public Integer getCarTypeId() {
        return carTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_info.car_type_id
     *
     * @param carTypeId the value for tbl_car_info.car_type_id
     *
     * @mbggenerated
     */
    public void setCarTypeId(Integer carTypeId) {
        this.carTypeId = carTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_info.car_level_id
     *
     * @return the value of tbl_car_info.car_level_id
     *
     * @mbggenerated
     */
    public Integer getCarLevelId() {
        return carLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_info.car_level_id
     *
     * @param carLevelId the value for tbl_car_info.car_level_id
     *
     * @mbggenerated
     */
    public void setCarLevelId(Integer carLevelId) {
        this.carLevelId = carLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_info.regist_date
     *
     * @return the value of tbl_car_info.regist_date
     *
     * @mbggenerated
     */
    public Date getRegistDate() {
        return registDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_info.regist_date
     *
     * @param registDate the value for tbl_car_info.regist_date
     *
     * @mbggenerated
     */
    public void setRegistDate(Date registDate) {
        this.registDate = registDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_info.insurance_start_date
     *
     * @return the value of tbl_car_info.insurance_start_date
     *
     * @mbggenerated
     */
    public Date getInsuranceStartDate() {
        return insuranceStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_info.insurance_start_date
     *
     * @param insuranceStartDate the value for tbl_car_info.insurance_start_date
     *
     * @mbggenerated
     */
    public void setInsuranceStartDate(Date insuranceStartDate) {
        this.insuranceStartDate = insuranceStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_info.insurance_end_date
     *
     * @return the value of tbl_car_info.insurance_end_date
     *
     * @mbggenerated
     */
    public Date getInsuranceEndDate() {
        return insuranceEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_info.insurance_end_date
     *
     * @param insuranceEndDate the value for tbl_car_info.insurance_end_date
     *
     * @mbggenerated
     */
    public void setInsuranceEndDate(Date insuranceEndDate) {
        this.insuranceEndDate = insuranceEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_info.annual_end_date
     *
     * @return the value of tbl_car_info.annual_end_date
     *
     * @mbggenerated
     */
    public Date getAnnualEndDate() {
        return annualEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_info.annual_end_date
     *
     * @param annualEndDate the value for tbl_car_info.annual_end_date
     *
     * @mbggenerated
     */
    public void setAnnualEndDate(Date annualEndDate) {
        this.annualEndDate = annualEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_info.car_license_img
     *
     * @return the value of tbl_car_info.car_license_img
     *
     * @mbggenerated
     */
    public String getCarLicenseImg() {
        return carLicenseImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_info.car_license_img
     *
     * @param carLicenseImg the value for tbl_car_info.car_license_img
     *
     * @mbggenerated
     */
    public void setCarLicenseImg(String carLicenseImg) {
        this.carLicenseImg = carLicenseImg == null ? null : carLicenseImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_info.is_free_order
     *
     * @return the value of tbl_car_info.is_free_order
     *
     * @mbggenerated
     */
    public Integer getIsFreeOrder() {
        return isFreeOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_info.is_free_order
     *
     * @param isFreeOrder the value for tbl_car_info.is_free_order
     *
     * @mbggenerated
     */
    public void setIsFreeOrder(Integer isFreeOrder) {
        this.isFreeOrder = isFreeOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_info.remark
     *
     * @return the value of tbl_car_info.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_info.remark
     *
     * @param remark the value for tbl_car_info.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_info.use_status
     *
     * @return the value of tbl_car_info.use_status
     *
     * @mbggenerated
     */
    public Integer getUseStatus() {
        return useStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_info.use_status
     *
     * @param useStatus the value for tbl_car_info.use_status
     *
     * @mbggenerated
     */
    public void setUseStatus(Integer useStatus) {
        this.useStatus = useStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_info.large_screen_device_code
     *
     * @return the value of tbl_car_info.large_screen_device_code
     *
     * @mbggenerated
     */
    public String getLargeScreenDeviceCode() {
        return largeScreenDeviceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_info.large_screen_device_code
     *
     * @param largeScreenDeviceCode the value for tbl_car_info.large_screen_device_code
     *
     * @mbggenerated
     */
    public void setLargeScreenDeviceCode(String largeScreenDeviceCode) {
        this.largeScreenDeviceCode = largeScreenDeviceCode == null ? null : largeScreenDeviceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_info.large_screen_device_brand
     *
     * @return the value of tbl_car_info.large_screen_device_brand
     *
     * @mbggenerated
     */
    public String getLargeScreenDeviceBrand() {
        return largeScreenDeviceBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_info.large_screen_device_brand
     *
     * @param largeScreenDeviceBrand the value for tbl_car_info.large_screen_device_brand
     *
     * @mbggenerated
     */
    public void setLargeScreenDeviceBrand(String largeScreenDeviceBrand) {
        this.largeScreenDeviceBrand = largeScreenDeviceBrand == null ? null : largeScreenDeviceBrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_info.car_screen_device_code
     *
     * @return the value of tbl_car_info.car_screen_device_code
     *
     * @mbggenerated
     */
    public String getCarScreenDeviceCode() {
        return carScreenDeviceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_info.car_screen_device_code
     *
     * @param carScreenDeviceCode the value for tbl_car_info.car_screen_device_code
     *
     * @mbggenerated
     */
    public void setCarScreenDeviceCode(String carScreenDeviceCode) {
        this.carScreenDeviceCode = carScreenDeviceCode == null ? null : carScreenDeviceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_info.car_screen_device_brand
     *
     * @return the value of tbl_car_info.car_screen_device_brand
     *
     * @mbggenerated
     */
    public String getCarScreenDeviceBrand() {
        return carScreenDeviceBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_info.car_screen_device_brand
     *
     * @param carScreenDeviceBrand the value for tbl_car_info.car_screen_device_brand
     *
     * @mbggenerated
     */
    public void setCarScreenDeviceBrand(String carScreenDeviceBrand) {
        this.carScreenDeviceBrand = carScreenDeviceBrand == null ? null : carScreenDeviceBrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_info.operator_id
     *
     * @return the value of tbl_car_info.operator_id
     *
     * @mbggenerated
     */
    public Integer getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_info.operator_id
     *
     * @param operatorId the value for tbl_car_info.operator_id
     *
     * @mbggenerated
     */
    public void setOperatorId(Integer operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_info.total_mile
     *
     * @return the value of tbl_car_info.total_mile
     *
     * @mbggenerated
     */
    public Integer getTotalMile() {
        return totalMile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_info.total_mile
     *
     * @param totalMile the value for tbl_car_info.total_mile
     *
     * @mbggenerated
     */
    public void setTotalMile(Integer totalMile) {
        this.totalMile = totalMile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_info.asset_coding
     *
     * @return the value of tbl_car_info.asset_coding
     *
     * @mbggenerated
     */
    public String getAssetCoding() {
        return assetCoding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_info.asset_coding
     *
     * @param assetCoding the value for tbl_car_info.asset_coding
     *
     * @mbggenerated
     */
    public void setAssetCoding(String assetCoding) {
        this.assetCoding = assetCoding == null ? null : assetCoding.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_info.create_time
     *
     * @return the value of tbl_car_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_info.create_time
     *
     * @param createTime the value for tbl_car_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_info.update_time
     *
     * @return the value of tbl_car_info.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_info.update_time
     *
     * @param updateTime the value for tbl_car_info.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}