package com.online.taxi.entity;

import java.util.Date;

public class CarType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_type.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_type.brand
     *
     * @mbggenerated
     */
    private String brand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_type.model
     *
     * @mbggenerated
     */
    private String model;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_type.seats
     *
     * @mbggenerated
     */
    private Byte seats;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_type.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_type.type_desc
     *
     * @mbggenerated
     */
    private String typeDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_type.img_url
     *
     * @mbggenerated
     */
    private String imgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_type.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_type.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_type.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_car_type.operator_id
     *
     * @mbggenerated
     */
    private Integer operatorId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_type.id
     *
     * @return the value of tbl_car_type.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_type.id
     *
     * @param id the value for tbl_car_type.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_type.brand
     *
     * @return the value of tbl_car_type.brand
     *
     * @mbggenerated
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_type.brand
     *
     * @param brand the value for tbl_car_type.brand
     *
     * @mbggenerated
     */
    public void setBrand(String brand) {
        this.brand = brand == null ? null : brand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_type.model
     *
     * @return the value of tbl_car_type.model
     *
     * @mbggenerated
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_type.model
     *
     * @param model the value for tbl_car_type.model
     *
     * @mbggenerated
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_type.seats
     *
     * @return the value of tbl_car_type.seats
     *
     * @mbggenerated
     */
    public Byte getSeats() {
        return seats;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_type.seats
     *
     * @param seats the value for tbl_car_type.seats
     *
     * @mbggenerated
     */
    public void setSeats(Byte seats) {
        this.seats = seats;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_type.city
     *
     * @return the value of tbl_car_type.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_type.city
     *
     * @param city the value for tbl_car_type.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_type.type_desc
     *
     * @return the value of tbl_car_type.type_desc
     *
     * @mbggenerated
     */
    public String getTypeDesc() {
        return typeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_type.type_desc
     *
     * @param typeDesc the value for tbl_car_type.type_desc
     *
     * @mbggenerated
     */
    public void setTypeDesc(String typeDesc) {
        this.typeDesc = typeDesc == null ? null : typeDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_type.img_url
     *
     * @return the value of tbl_car_type.img_url
     *
     * @mbggenerated
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_type.img_url
     *
     * @param imgUrl the value for tbl_car_type.img_url
     *
     * @mbggenerated
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_type.status
     *
     * @return the value of tbl_car_type.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_type.status
     *
     * @param status the value for tbl_car_type.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_type.create_time
     *
     * @return the value of tbl_car_type.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_type.create_time
     *
     * @param createTime the value for tbl_car_type.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_type.update_time
     *
     * @return the value of tbl_car_type.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_type.update_time
     *
     * @param updateTime the value for tbl_car_type.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_car_type.operator_id
     *
     * @return the value of tbl_car_type.operator_id
     *
     * @mbggenerated
     */
    public Integer getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_car_type.operator_id
     *
     * @param operatorId the value for tbl_car_type.operator_id
     *
     * @mbggenerated
     */
    public void setOperatorId(Integer operatorId) {
        this.operatorId = operatorId;
    }
}