package com.online.taxi.entity;

import java.util.Date;

public class DriverRate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_driver_rate.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_driver_rate.driver_id
     *
     * @mbggenerated
     */
    private Integer driverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_driver_rate.grade
     *
     * @mbggenerated
     */
    private Integer grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_driver_rate.test_date
     *
     * @mbggenerated
     */
    private Date testDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_driver_rate.test_department
     *
     * @mbggenerated
     */
    private String testDepartment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_driver_rate.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_driver_rate.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_driver_rate.id
     *
     * @return the value of tbl_driver_rate.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_driver_rate.id
     *
     * @param id the value for tbl_driver_rate.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_driver_rate.driver_id
     *
     * @return the value of tbl_driver_rate.driver_id
     *
     * @mbggenerated
     */
    public Integer getDriverId() {
        return driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_driver_rate.driver_id
     *
     * @param driverId the value for tbl_driver_rate.driver_id
     *
     * @mbggenerated
     */
    public void setDriverId(Integer driverId) {
        this.driverId = driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_driver_rate.grade
     *
     * @return the value of tbl_driver_rate.grade
     *
     * @mbggenerated
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_driver_rate.grade
     *
     * @param grade the value for tbl_driver_rate.grade
     *
     * @mbggenerated
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_driver_rate.test_date
     *
     * @return the value of tbl_driver_rate.test_date
     *
     * @mbggenerated
     */
    public Date getTestDate() {
        return testDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_driver_rate.test_date
     *
     * @param testDate the value for tbl_driver_rate.test_date
     *
     * @mbggenerated
     */
    public void setTestDate(Date testDate) {
        this.testDate = testDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_driver_rate.test_department
     *
     * @return the value of tbl_driver_rate.test_department
     *
     * @mbggenerated
     */
    public String getTestDepartment() {
        return testDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_driver_rate.test_department
     *
     * @param testDepartment the value for tbl_driver_rate.test_department
     *
     * @mbggenerated
     */
    public void setTestDepartment(String testDepartment) {
        this.testDepartment = testDepartment == null ? null : testDepartment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_driver_rate.create_time
     *
     * @return the value of tbl_driver_rate.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_driver_rate.create_time
     *
     * @param createTime the value for tbl_driver_rate.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_driver_rate.update_time
     *
     * @return the value of tbl_driver_rate.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_driver_rate.update_time
     *
     * @param updateTime the value for tbl_driver_rate.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}