package com.online.taxi.entity;

import java.util.Date;

public class DriverLicenceInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_driver_licence_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_driver_licence_info.driver_id
     *
     * @mbggenerated
     */
    private Integer driverId;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_driver_licence_info.main_driving_license
     *
     * @mbggenerated
     */
    private String mainDrivingLicense;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_driver_licence_info.vice_driving_license
     *
     * @mbggenerated
     */
    private String viceDrivingLicense;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_driver_licence_info.all_driving_license
     *
     * @mbggenerated
     */
    private String allDrivingLicense;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_driver_licence_info.group_driving_license
     *
     * @mbggenerated
     */
    private String groupDrivingLicense;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_driver_licence_info.identity_card_id
     *
     * @mbggenerated
     */
    private String identityCardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_driver_licence_info.main_idcard_license
     *
     * @mbggenerated
     */
    private String mainIdcardLicense;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_driver_licence_info.vice_idcard_license
     *
     * @mbggenerated
     */
    private String viceIdcardLicense;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_driver_licence_info.group_idcard_license
     *
     * @mbggenerated
     */
    private String groupIdcardLicense;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_driver_licence_info.plate_number
     *
     * @mbggenerated
     */
    private String plateNumber;
    private Date createTime;
    private Date updateTime;

    public Date getCreateTime() {
        return createTime;
    }

    public DriverLicenceInfo setCreateTime(Date createTime) {
        this.createTime = createTime;
        return this;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public DriverLicenceInfo setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_driver_licence_info.id
     *
     * @return the value of tbl_driver_licence_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_driver_licence_info.id
     *
     * @param id the value for tbl_driver_licence_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_driver_licence_info.driver_id
     *
     * @return the value of tbl_driver_licence_info.driver_id
     *
     * @mbggenerated
     */
    public Integer getDriverId() {
        return driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_driver_licence_info.driver_id
     *
     * @param driverId the value for tbl_driver_licence_info.driver_id
     *
     * @mbggenerated
     */
    public void setDriverId(Integer driverId) {
        this.driverId = driverId;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_driver_licence_info.main_driving_license
     *
     * @return the value of tbl_driver_licence_info.main_driving_license
     *
     * @mbggenerated
     */
    public String getMainDrivingLicense() {
        return mainDrivingLicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_driver_licence_info.main_driving_license
     *
     * @param mainDrivingLicense the value for tbl_driver_licence_info.main_driving_license
     *
     * @mbggenerated
     */
    public void setMainDrivingLicense(String mainDrivingLicense) {
        this.mainDrivingLicense = mainDrivingLicense == null ? null : mainDrivingLicense.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_driver_licence_info.vice_driving_license
     *
     * @return the value of tbl_driver_licence_info.vice_driving_license
     *
     * @mbggenerated
     */
    public String getViceDrivingLicense() {
        return viceDrivingLicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_driver_licence_info.vice_driving_license
     *
     * @param viceDrivingLicense the value for tbl_driver_licence_info.vice_driving_license
     *
     * @mbggenerated
     */
    public void setViceDrivingLicense(String viceDrivingLicense) {
        this.viceDrivingLicense = viceDrivingLicense == null ? null : viceDrivingLicense.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_driver_licence_info.all_driving_license
     *
     * @return the value of tbl_driver_licence_info.all_driving_license
     *
     * @mbggenerated
     */
    public String getAllDrivingLicense() {
        return allDrivingLicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_driver_licence_info.all_driving_license
     *
     * @param allDrivingLicense the value for tbl_driver_licence_info.all_driving_license
     *
     * @mbggenerated
     */
    public void setAllDrivingLicense(String allDrivingLicense) {
        this.allDrivingLicense = allDrivingLicense == null ? null : allDrivingLicense.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_driver_licence_info.group_driving_license
     *
     * @return the value of tbl_driver_licence_info.group_driving_license
     *
     * @mbggenerated
     */
    public String getGroupDrivingLicense() {
        return groupDrivingLicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_driver_licence_info.group_driving_license
     *
     * @param groupDrivingLicense the value for tbl_driver_licence_info.group_driving_license
     *
     * @mbggenerated
     */
    public void setGroupDrivingLicense(String groupDrivingLicense) {
        this.groupDrivingLicense = groupDrivingLicense == null ? null : groupDrivingLicense.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_driver_licence_info.identity_card_id
     *
     * @return the value of tbl_driver_licence_info.identity_card_id
     *
     * @mbggenerated
     */
    public String getIdentityCardId() {
        return identityCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_driver_licence_info.identity_card_id
     *
     * @param identityCardId the value for tbl_driver_licence_info.identity_card_id
     *
     * @mbggenerated
     */
    public void setIdentityCardId(String identityCardId) {
        this.identityCardId = identityCardId == null ? null : identityCardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_driver_licence_info.main_idcard_license
     *
     * @return the value of tbl_driver_licence_info.main_idcard_license
     *
     * @mbggenerated
     */
    public String getMainIdcardLicense() {
        return mainIdcardLicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_driver_licence_info.main_idcard_license
     *
     * @param mainIdcardLicense the value for tbl_driver_licence_info.main_idcard_license
     *
     * @mbggenerated
     */
    public void setMainIdcardLicense(String mainIdcardLicense) {
        this.mainIdcardLicense = mainIdcardLicense == null ? null : mainIdcardLicense.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_driver_licence_info.vice_idcard_license
     *
     * @return the value of tbl_driver_licence_info.vice_idcard_license
     *
     * @mbggenerated
     */
    public String getViceIdcardLicense() {
        return viceIdcardLicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_driver_licence_info.vice_idcard_license
     *
     * @param viceIdcardLicense the value for tbl_driver_licence_info.vice_idcard_license
     *
     * @mbggenerated
     */
    public void setViceIdcardLicense(String viceIdcardLicense) {
        this.viceIdcardLicense = viceIdcardLicense == null ? null : viceIdcardLicense.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_driver_licence_info.group_idcard_license
     *
     * @return the value of tbl_driver_licence_info.group_idcard_license
     *
     * @mbggenerated
     */
    public String getGroupIdcardLicense() {
        return groupIdcardLicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_driver_licence_info.group_idcard_license
     *
     * @param groupIdcardLicense the value for tbl_driver_licence_info.group_idcard_license
     *
     * @mbggenerated
     */
    public void setGroupIdcardLicense(String groupIdcardLicense) {
        this.groupIdcardLicense = groupIdcardLicense == null ? null : groupIdcardLicense.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_driver_licence_info.plate_number
     *
     * @return the value of tbl_driver_licence_info.plate_number
     *
     * @mbggenerated
     */
    public String getPlateNumber() {
        return plateNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_driver_licence_info.plate_number
     *
     * @param plateNumber the value for tbl_driver_licence_info.plate_number
     *
     * @mbggenerated
     */
    public void setPlateNumber(String plateNumber) {
        this.plateNumber = plateNumber == null ? null : plateNumber.trim();
    }
}
