package com.online.taxi.entity;

import java.util.Date;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.order_number
     *
     * @mbggenerated
     */
    private String orderNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.passenger_info_id
     *
     * @mbggenerated
     */
    private Integer passengerInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.passenger_phone
     *
     * @mbggenerated
     */
    private String passengerPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.device_code
     *
     * @mbggenerated
     */
    private String deviceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.driver_id
     *
     * @mbggenerated
     */
    private Integer driverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.driver_status
     *
     * @mbggenerated
     */
    private Integer driverStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.driver_phone
     *
     * @mbggenerated
     */
    private String driverPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.car_id
     *
     * @mbggenerated
     */
    private Integer carId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.plate_number
     *
     * @mbggenerated
     */
    private String plateNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.user_longitude
     *
     * @mbggenerated
     */
    private String userLongitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.user_latitude
     *
     * @mbggenerated
     */
    private String userLatitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.start_longitude
     *
     * @mbggenerated
     */
    private String startLongitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.start_latitude
     *
     * @mbggenerated
     */
    private String startLatitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.start_address
     *
     * @mbggenerated
     */
    private String startAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.end_address
     *
     * @mbggenerated
     */
    private String endAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.start_time
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.order_start_time
     *
     * @mbggenerated
     */
    private Date orderStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.end_longitude
     *
     * @mbggenerated
     */
    private String endLongitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.end_latitude
     *
     * @mbggenerated
     */
    private String endLatitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.driver_grab_time
     *
     * @mbggenerated
     */
    private Date driverGrabTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.driver_start_time
     *
     * @mbggenerated
     */
    private Date driverStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.driver_arrived_time
     *
     * @mbggenerated
     */
    private Date driverArrivedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.pick_up_passenger_time
     *
     * @mbggenerated
     */
    private Date pickUpPassengerTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.pick_up_passenger_longitude
     *
     * @mbggenerated
     */
    private String pickUpPassengerLongitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.pick_up_passenger_latitude
     *
     * @mbggenerated
     */
    private String pickUpPassengerLatitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.pick_up_passenger_address
     *
     * @mbggenerated
     */
    private String pickUpPassengerAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.receive_passenger_time
     *
     * @mbggenerated
     */
    private Date receivePassengerTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.receive_passenger_longitude
     *
     * @mbggenerated
     */
    private String receivePassengerLongitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.receive_passenger_latitude
     *
     * @mbggenerated
     */
    private String receivePassengerLatitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.receive_passenger_address
     *
     * @mbggenerated
     */
    private String receivePassengerAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.passenger_getoff_time
     *
     * @mbggenerated
     */
    private Date passengerGetoffTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.passenger_getoff_longitude
     *
     * @mbggenerated
     */
    private String passengerGetoffLongitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.passenger_getoff_latitude
     *
     * @mbggenerated
     */
    private String passengerGetoffLatitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.passenger_getoff_address
     *
     * @mbggenerated
     */
    private String passengerGetoffAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.other_name
     *
     * @mbggenerated
     */
    private String otherName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.other_phone
     *
     * @mbggenerated
     */
    private String otherPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.order_type
     *
     * @mbggenerated
     */
    private Integer orderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.service_type
     *
     * @mbggenerated
     */
    private Integer serviceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.order_channel
     *
     * @mbggenerated
     */
    private Integer orderChannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.user_feature
     *
     * @mbggenerated
     */
    private String userFeature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.transaction_id
     *
     * @mbggenerated
     */
    private String transactionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.mapping_id
     *
     * @mbggenerated
     */
    private String mappingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.mapping_number
     *
     * @mbggenerated
     */
    private String mappingNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.other_mapping_id
     *
     * @mbggenerated
     */
    private String otherMappingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.other_mapping_number
     *
     * @mbggenerated
     */
    private String otherMappingNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.merchant_id
     *
     * @mbggenerated
     */
    private String merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.is_evaluate_driver
     *
     * @mbggenerated
     */
    private Integer isEvaluateDriver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.is_evaluate
     *
     * @mbggenerated
     */
    private Integer isEvaluate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.invoice_type
     *
     * @mbggenerated
     */
    private Integer invoiceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.is_annotate
     *
     * @mbggenerated
     */
    private Integer isAnnotate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.source
     *
     * @mbggenerated
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.use_coupon
     *
     * @mbggenerated
     */
    private Integer useCoupon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.cancel_order_type
     *
     * @mbggenerated
     */
    private Integer cancelOrderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.pay_type
     *
     * @mbggenerated
     */
    private Integer payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.is_paid
     *
     * @mbggenerated
     */
    private Integer isPaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.is_cancel
     *
     * @mbggenerated
     */
    private Integer isCancel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.is_adjust
     *
     * @mbggenerated
     */
    private Integer isAdjust;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.is_dissent
     *
     * @mbggenerated
     */
    private Integer isDissent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.is_manual
     *
     * @mbggenerated
     */
    private Integer isManual;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.is_following
     *
     * @mbggenerated
     */
    private Integer isFollowing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.is_fake_success
     *
     * @mbggenerated
     */
    private Integer isFakeSuccess;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.memo
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.is_use_risk
     *
     * @mbggenerated
     */
    private Integer isUseRisk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.id
     *
     * @return the value of tbl_order.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.id
     *
     * @param id the value for tbl_order.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.order_number
     *
     * @return the value of tbl_order.order_number
     *
     * @mbggenerated
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.order_number
     *
     * @param orderNumber the value for tbl_order.order_number
     *
     * @mbggenerated
     */
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber == null ? null : orderNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.passenger_info_id
     *
     * @return the value of tbl_order.passenger_info_id
     *
     * @mbggenerated
     */
    public Integer getPassengerInfoId() {
        return passengerInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.passenger_info_id
     *
     * @param passengerInfoId the value for tbl_order.passenger_info_id
     *
     * @mbggenerated
     */
    public void setPassengerInfoId(Integer passengerInfoId) {
        this.passengerInfoId = passengerInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.passenger_phone
     *
     * @return the value of tbl_order.passenger_phone
     *
     * @mbggenerated
     */
    public String getPassengerPhone() {
        return passengerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.passenger_phone
     *
     * @param passengerPhone the value for tbl_order.passenger_phone
     *
     * @mbggenerated
     */
    public void setPassengerPhone(String passengerPhone) {
        this.passengerPhone = passengerPhone == null ? null : passengerPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.device_code
     *
     * @return the value of tbl_order.device_code
     *
     * @mbggenerated
     */
    public String getDeviceCode() {
        return deviceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.device_code
     *
     * @param deviceCode the value for tbl_order.device_code
     *
     * @mbggenerated
     */
    public void setDeviceCode(String deviceCode) {
        this.deviceCode = deviceCode == null ? null : deviceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.driver_id
     *
     * @return the value of tbl_order.driver_id
     *
     * @mbggenerated
     */
    public Integer getDriverId() {
        return driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.driver_id
     *
     * @param driverId the value for tbl_order.driver_id
     *
     * @mbggenerated
     */
    public void setDriverId(Integer driverId) {
        this.driverId = driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.driver_status
     *
     * @return the value of tbl_order.driver_status
     *
     * @mbggenerated
     */
    public Integer getDriverStatus() {
        return driverStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.driver_status
     *
     * @param driverStatus the value for tbl_order.driver_status
     *
     * @mbggenerated
     */
    public void setDriverStatus(Integer driverStatus) {
        this.driverStatus = driverStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.driver_phone
     *
     * @return the value of tbl_order.driver_phone
     *
     * @mbggenerated
     */
    public String getDriverPhone() {
        return driverPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.driver_phone
     *
     * @param driverPhone the value for tbl_order.driver_phone
     *
     * @mbggenerated
     */
    public void setDriverPhone(String driverPhone) {
        this.driverPhone = driverPhone == null ? null : driverPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.car_id
     *
     * @return the value of tbl_order.car_id
     *
     * @mbggenerated
     */
    public Integer getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.car_id
     *
     * @param carId the value for tbl_order.car_id
     *
     * @mbggenerated
     */
    public void setCarId(Integer carId) {
        this.carId = carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.plate_number
     *
     * @return the value of tbl_order.plate_number
     *
     * @mbggenerated
     */
    public String getPlateNumber() {
        return plateNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.plate_number
     *
     * @param plateNumber the value for tbl_order.plate_number
     *
     * @mbggenerated
     */
    public void setPlateNumber(String plateNumber) {
        this.plateNumber = plateNumber == null ? null : plateNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.user_longitude
     *
     * @return the value of tbl_order.user_longitude
     *
     * @mbggenerated
     */
    public String getUserLongitude() {
        return userLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.user_longitude
     *
     * @param userLongitude the value for tbl_order.user_longitude
     *
     * @mbggenerated
     */
    public void setUserLongitude(String userLongitude) {
        this.userLongitude = userLongitude == null ? null : userLongitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.user_latitude
     *
     * @return the value of tbl_order.user_latitude
     *
     * @mbggenerated
     */
    public String getUserLatitude() {
        return userLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.user_latitude
     *
     * @param userLatitude the value for tbl_order.user_latitude
     *
     * @mbggenerated
     */
    public void setUserLatitude(String userLatitude) {
        this.userLatitude = userLatitude == null ? null : userLatitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.start_longitude
     *
     * @return the value of tbl_order.start_longitude
     *
     * @mbggenerated
     */
    public String getStartLongitude() {
        return startLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.start_longitude
     *
     * @param startLongitude the value for tbl_order.start_longitude
     *
     * @mbggenerated
     */
    public void setStartLongitude(String startLongitude) {
        this.startLongitude = startLongitude == null ? null : startLongitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.start_latitude
     *
     * @return the value of tbl_order.start_latitude
     *
     * @mbggenerated
     */
    public String getStartLatitude() {
        return startLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.start_latitude
     *
     * @param startLatitude the value for tbl_order.start_latitude
     *
     * @mbggenerated
     */
    public void setStartLatitude(String startLatitude) {
        this.startLatitude = startLatitude == null ? null : startLatitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.start_address
     *
     * @return the value of tbl_order.start_address
     *
     * @mbggenerated
     */
    public String getStartAddress() {
        return startAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.start_address
     *
     * @param startAddress the value for tbl_order.start_address
     *
     * @mbggenerated
     */
    public void setStartAddress(String startAddress) {
        this.startAddress = startAddress == null ? null : startAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.end_address
     *
     * @return the value of tbl_order.end_address
     *
     * @mbggenerated
     */
    public String getEndAddress() {
        return endAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.end_address
     *
     * @param endAddress the value for tbl_order.end_address
     *
     * @mbggenerated
     */
    public void setEndAddress(String endAddress) {
        this.endAddress = endAddress == null ? null : endAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.start_time
     *
     * @return the value of tbl_order.start_time
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.start_time
     *
     * @param startTime the value for tbl_order.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.order_start_time
     *
     * @return the value of tbl_order.order_start_time
     *
     * @mbggenerated
     */
    public Date getOrderStartTime() {
        return orderStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.order_start_time
     *
     * @param orderStartTime the value for tbl_order.order_start_time
     *
     * @mbggenerated
     */
    public void setOrderStartTime(Date orderStartTime) {
        this.orderStartTime = orderStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.end_longitude
     *
     * @return the value of tbl_order.end_longitude
     *
     * @mbggenerated
     */
    public String getEndLongitude() {
        return endLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.end_longitude
     *
     * @param endLongitude the value for tbl_order.end_longitude
     *
     * @mbggenerated
     */
    public void setEndLongitude(String endLongitude) {
        this.endLongitude = endLongitude == null ? null : endLongitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.end_latitude
     *
     * @return the value of tbl_order.end_latitude
     *
     * @mbggenerated
     */
    public String getEndLatitude() {
        return endLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.end_latitude
     *
     * @param endLatitude the value for tbl_order.end_latitude
     *
     * @mbggenerated
     */
    public void setEndLatitude(String endLatitude) {
        this.endLatitude = endLatitude == null ? null : endLatitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.driver_grab_time
     *
     * @return the value of tbl_order.driver_grab_time
     *
     * @mbggenerated
     */
    public Date getDriverGrabTime() {
        return driverGrabTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.driver_grab_time
     *
     * @param driverGrabTime the value for tbl_order.driver_grab_time
     *
     * @mbggenerated
     */
    public void setDriverGrabTime(Date driverGrabTime) {
        this.driverGrabTime = driverGrabTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.driver_start_time
     *
     * @return the value of tbl_order.driver_start_time
     *
     * @mbggenerated
     */
    public Date getDriverStartTime() {
        return driverStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.driver_start_time
     *
     * @param driverStartTime the value for tbl_order.driver_start_time
     *
     * @mbggenerated
     */
    public void setDriverStartTime(Date driverStartTime) {
        this.driverStartTime = driverStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.driver_arrived_time
     *
     * @return the value of tbl_order.driver_arrived_time
     *
     * @mbggenerated
     */
    public Date getDriverArrivedTime() {
        return driverArrivedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.driver_arrived_time
     *
     * @param driverArrivedTime the value for tbl_order.driver_arrived_time
     *
     * @mbggenerated
     */
    public void setDriverArrivedTime(Date driverArrivedTime) {
        this.driverArrivedTime = driverArrivedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.pick_up_passenger_time
     *
     * @return the value of tbl_order.pick_up_passenger_time
     *
     * @mbggenerated
     */
    public Date getPickUpPassengerTime() {
        return pickUpPassengerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.pick_up_passenger_time
     *
     * @param pickUpPassengerTime the value for tbl_order.pick_up_passenger_time
     *
     * @mbggenerated
     */
    public void setPickUpPassengerTime(Date pickUpPassengerTime) {
        this.pickUpPassengerTime = pickUpPassengerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.pick_up_passenger_longitude
     *
     * @return the value of tbl_order.pick_up_passenger_longitude
     *
     * @mbggenerated
     */
    public String getPickUpPassengerLongitude() {
        return pickUpPassengerLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.pick_up_passenger_longitude
     *
     * @param pickUpPassengerLongitude the value for tbl_order.pick_up_passenger_longitude
     *
     * @mbggenerated
     */
    public void setPickUpPassengerLongitude(String pickUpPassengerLongitude) {
        this.pickUpPassengerLongitude = pickUpPassengerLongitude == null ? null : pickUpPassengerLongitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.pick_up_passenger_latitude
     *
     * @return the value of tbl_order.pick_up_passenger_latitude
     *
     * @mbggenerated
     */
    public String getPickUpPassengerLatitude() {
        return pickUpPassengerLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.pick_up_passenger_latitude
     *
     * @param pickUpPassengerLatitude the value for tbl_order.pick_up_passenger_latitude
     *
     * @mbggenerated
     */
    public void setPickUpPassengerLatitude(String pickUpPassengerLatitude) {
        this.pickUpPassengerLatitude = pickUpPassengerLatitude == null ? null : pickUpPassengerLatitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.pick_up_passenger_address
     *
     * @return the value of tbl_order.pick_up_passenger_address
     *
     * @mbggenerated
     */
    public String getPickUpPassengerAddress() {
        return pickUpPassengerAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.pick_up_passenger_address
     *
     * @param pickUpPassengerAddress the value for tbl_order.pick_up_passenger_address
     *
     * @mbggenerated
     */
    public void setPickUpPassengerAddress(String pickUpPassengerAddress) {
        this.pickUpPassengerAddress = pickUpPassengerAddress == null ? null : pickUpPassengerAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.receive_passenger_time
     *
     * @return the value of tbl_order.receive_passenger_time
     *
     * @mbggenerated
     */
    public Date getReceivePassengerTime() {
        return receivePassengerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.receive_passenger_time
     *
     * @param receivePassengerTime the value for tbl_order.receive_passenger_time
     *
     * @mbggenerated
     */
    public void setReceivePassengerTime(Date receivePassengerTime) {
        this.receivePassengerTime = receivePassengerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.receive_passenger_longitude
     *
     * @return the value of tbl_order.receive_passenger_longitude
     *
     * @mbggenerated
     */
    public String getReceivePassengerLongitude() {
        return receivePassengerLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.receive_passenger_longitude
     *
     * @param receivePassengerLongitude the value for tbl_order.receive_passenger_longitude
     *
     * @mbggenerated
     */
    public void setReceivePassengerLongitude(String receivePassengerLongitude) {
        this.receivePassengerLongitude = receivePassengerLongitude == null ? null : receivePassengerLongitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.receive_passenger_latitude
     *
     * @return the value of tbl_order.receive_passenger_latitude
     *
     * @mbggenerated
     */
    public String getReceivePassengerLatitude() {
        return receivePassengerLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.receive_passenger_latitude
     *
     * @param receivePassengerLatitude the value for tbl_order.receive_passenger_latitude
     *
     * @mbggenerated
     */
    public void setReceivePassengerLatitude(String receivePassengerLatitude) {
        this.receivePassengerLatitude = receivePassengerLatitude == null ? null : receivePassengerLatitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.receive_passenger_address
     *
     * @return the value of tbl_order.receive_passenger_address
     *
     * @mbggenerated
     */
    public String getReceivePassengerAddress() {
        return receivePassengerAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.receive_passenger_address
     *
     * @param receivePassengerAddress the value for tbl_order.receive_passenger_address
     *
     * @mbggenerated
     */
    public void setReceivePassengerAddress(String receivePassengerAddress) {
        this.receivePassengerAddress = receivePassengerAddress == null ? null : receivePassengerAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.passenger_getoff_time
     *
     * @return the value of tbl_order.passenger_getoff_time
     *
     * @mbggenerated
     */
    public Date getPassengerGetoffTime() {
        return passengerGetoffTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.passenger_getoff_time
     *
     * @param passengerGetoffTime the value for tbl_order.passenger_getoff_time
     *
     * @mbggenerated
     */
    public void setPassengerGetoffTime(Date passengerGetoffTime) {
        this.passengerGetoffTime = passengerGetoffTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.passenger_getoff_longitude
     *
     * @return the value of tbl_order.passenger_getoff_longitude
     *
     * @mbggenerated
     */
    public String getPassengerGetoffLongitude() {
        return passengerGetoffLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.passenger_getoff_longitude
     *
     * @param passengerGetoffLongitude the value for tbl_order.passenger_getoff_longitude
     *
     * @mbggenerated
     */
    public void setPassengerGetoffLongitude(String passengerGetoffLongitude) {
        this.passengerGetoffLongitude = passengerGetoffLongitude == null ? null : passengerGetoffLongitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.passenger_getoff_latitude
     *
     * @return the value of tbl_order.passenger_getoff_latitude
     *
     * @mbggenerated
     */
    public String getPassengerGetoffLatitude() {
        return passengerGetoffLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.passenger_getoff_latitude
     *
     * @param passengerGetoffLatitude the value for tbl_order.passenger_getoff_latitude
     *
     * @mbggenerated
     */
    public void setPassengerGetoffLatitude(String passengerGetoffLatitude) {
        this.passengerGetoffLatitude = passengerGetoffLatitude == null ? null : passengerGetoffLatitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.passenger_getoff_address
     *
     * @return the value of tbl_order.passenger_getoff_address
     *
     * @mbggenerated
     */
    public String getPassengerGetoffAddress() {
        return passengerGetoffAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.passenger_getoff_address
     *
     * @param passengerGetoffAddress the value for tbl_order.passenger_getoff_address
     *
     * @mbggenerated
     */
    public void setPassengerGetoffAddress(String passengerGetoffAddress) {
        this.passengerGetoffAddress = passengerGetoffAddress == null ? null : passengerGetoffAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.other_name
     *
     * @return the value of tbl_order.other_name
     *
     * @mbggenerated
     */
    public String getOtherName() {
        return otherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.other_name
     *
     * @param otherName the value for tbl_order.other_name
     *
     * @mbggenerated
     */
    public void setOtherName(String otherName) {
        this.otherName = otherName == null ? null : otherName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.other_phone
     *
     * @return the value of tbl_order.other_phone
     *
     * @mbggenerated
     */
    public String getOtherPhone() {
        return otherPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.other_phone
     *
     * @param otherPhone the value for tbl_order.other_phone
     *
     * @mbggenerated
     */
    public void setOtherPhone(String otherPhone) {
        this.otherPhone = otherPhone == null ? null : otherPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.order_type
     *
     * @return the value of tbl_order.order_type
     *
     * @mbggenerated
     */
    public Integer getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.order_type
     *
     * @param orderType the value for tbl_order.order_type
     *
     * @mbggenerated
     */
    public void setOrderType(Integer orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.service_type
     *
     * @return the value of tbl_order.service_type
     *
     * @mbggenerated
     */
    public Integer getServiceType() {
        return serviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.service_type
     *
     * @param serviceType the value for tbl_order.service_type
     *
     * @mbggenerated
     */
    public void setServiceType(Integer serviceType) {
        this.serviceType = serviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.order_channel
     *
     * @return the value of tbl_order.order_channel
     *
     * @mbggenerated
     */
    public Integer getOrderChannel() {
        return orderChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.order_channel
     *
     * @param orderChannel the value for tbl_order.order_channel
     *
     * @mbggenerated
     */
    public void setOrderChannel(Integer orderChannel) {
        this.orderChannel = orderChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.status
     *
     * @return the value of tbl_order.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.status
     *
     * @param status the value for tbl_order.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.user_feature
     *
     * @return the value of tbl_order.user_feature
     *
     * @mbggenerated
     */
    public String getUserFeature() {
        return userFeature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.user_feature
     *
     * @param userFeature the value for tbl_order.user_feature
     *
     * @mbggenerated
     */
    public void setUserFeature(String userFeature) {
        this.userFeature = userFeature == null ? null : userFeature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.transaction_id
     *
     * @return the value of tbl_order.transaction_id
     *
     * @mbggenerated
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.transaction_id
     *
     * @param transactionId the value for tbl_order.transaction_id
     *
     * @mbggenerated
     */
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId == null ? null : transactionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.mapping_id
     *
     * @return the value of tbl_order.mapping_id
     *
     * @mbggenerated
     */
    public String getMappingId() {
        return mappingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.mapping_id
     *
     * @param mappingId the value for tbl_order.mapping_id
     *
     * @mbggenerated
     */
    public void setMappingId(String mappingId) {
        this.mappingId = mappingId == null ? null : mappingId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.mapping_number
     *
     * @return the value of tbl_order.mapping_number
     *
     * @mbggenerated
     */
    public String getMappingNumber() {
        return mappingNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.mapping_number
     *
     * @param mappingNumber the value for tbl_order.mapping_number
     *
     * @mbggenerated
     */
    public void setMappingNumber(String mappingNumber) {
        this.mappingNumber = mappingNumber == null ? null : mappingNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.other_mapping_id
     *
     * @return the value of tbl_order.other_mapping_id
     *
     * @mbggenerated
     */
    public String getOtherMappingId() {
        return otherMappingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.other_mapping_id
     *
     * @param otherMappingId the value for tbl_order.other_mapping_id
     *
     * @mbggenerated
     */
    public void setOtherMappingId(String otherMappingId) {
        this.otherMappingId = otherMappingId == null ? null : otherMappingId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.other_mapping_number
     *
     * @return the value of tbl_order.other_mapping_number
     *
     * @mbggenerated
     */
    public String getOtherMappingNumber() {
        return otherMappingNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.other_mapping_number
     *
     * @param otherMappingNumber the value for tbl_order.other_mapping_number
     *
     * @mbggenerated
     */
    public void setOtherMappingNumber(String otherMappingNumber) {
        this.otherMappingNumber = otherMappingNumber == null ? null : otherMappingNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.merchant_id
     *
     * @return the value of tbl_order.merchant_id
     *
     * @mbggenerated
     */
    public String getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.merchant_id
     *
     * @param merchantId the value for tbl_order.merchant_id
     *
     * @mbggenerated
     */
    public void setMerchantId(String merchantId) {
        this.merchantId = merchantId == null ? null : merchantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.is_evaluate_driver
     *
     * @return the value of tbl_order.is_evaluate_driver
     *
     * @mbggenerated
     */
    public Integer getIsEvaluateDriver() {
        return isEvaluateDriver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.is_evaluate_driver
     *
     * @param isEvaluateDriver the value for tbl_order.is_evaluate_driver
     *
     * @mbggenerated
     */
    public void setIsEvaluateDriver(Integer isEvaluateDriver) {
        this.isEvaluateDriver = isEvaluateDriver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.is_evaluate
     *
     * @return the value of tbl_order.is_evaluate
     *
     * @mbggenerated
     */
    public Integer getIsEvaluate() {
        return isEvaluate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.is_evaluate
     *
     * @param isEvaluate the value for tbl_order.is_evaluate
     *
     * @mbggenerated
     */
    public void setIsEvaluate(Integer isEvaluate) {
        this.isEvaluate = isEvaluate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.invoice_type
     *
     * @return the value of tbl_order.invoice_type
     *
     * @mbggenerated
     */
    public Integer getInvoiceType() {
        return invoiceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.invoice_type
     *
     * @param invoiceType the value for tbl_order.invoice_type
     *
     * @mbggenerated
     */
    public void setInvoiceType(Integer invoiceType) {
        this.invoiceType = invoiceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.is_annotate
     *
     * @return the value of tbl_order.is_annotate
     *
     * @mbggenerated
     */
    public Integer getIsAnnotate() {
        return isAnnotate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.is_annotate
     *
     * @param isAnnotate the value for tbl_order.is_annotate
     *
     * @mbggenerated
     */
    public void setIsAnnotate(Integer isAnnotate) {
        this.isAnnotate = isAnnotate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.source
     *
     * @return the value of tbl_order.source
     *
     * @mbggenerated
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.source
     *
     * @param source the value for tbl_order.source
     *
     * @mbggenerated
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.use_coupon
     *
     * @return the value of tbl_order.use_coupon
     *
     * @mbggenerated
     */
    public Integer getUseCoupon() {
        return useCoupon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.use_coupon
     *
     * @param useCoupon the value for tbl_order.use_coupon
     *
     * @mbggenerated
     */
    public void setUseCoupon(Integer useCoupon) {
        this.useCoupon = useCoupon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.cancel_order_type
     *
     * @return the value of tbl_order.cancel_order_type
     *
     * @mbggenerated
     */
    public Integer getCancelOrderType() {
        return cancelOrderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.cancel_order_type
     *
     * @param cancelOrderType the value for tbl_order.cancel_order_type
     *
     * @mbggenerated
     */
    public void setCancelOrderType(Integer cancelOrderType) {
        this.cancelOrderType = cancelOrderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.pay_type
     *
     * @return the value of tbl_order.pay_type
     *
     * @mbggenerated
     */
    public Integer getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.pay_type
     *
     * @param payType the value for tbl_order.pay_type
     *
     * @mbggenerated
     */
    public void setPayType(Integer payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.is_paid
     *
     * @return the value of tbl_order.is_paid
     *
     * @mbggenerated
     */
    public Integer getIsPaid() {
        return isPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.is_paid
     *
     * @param isPaid the value for tbl_order.is_paid
     *
     * @mbggenerated
     */
    public void setIsPaid(Integer isPaid) {
        this.isPaid = isPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.is_cancel
     *
     * @return the value of tbl_order.is_cancel
     *
     * @mbggenerated
     */
    public Integer getIsCancel() {
        return isCancel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.is_cancel
     *
     * @param isCancel the value for tbl_order.is_cancel
     *
     * @mbggenerated
     */
    public void setIsCancel(Integer isCancel) {
        this.isCancel = isCancel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.is_adjust
     *
     * @return the value of tbl_order.is_adjust
     *
     * @mbggenerated
     */
    public Integer getIsAdjust() {
        return isAdjust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.is_adjust
     *
     * @param isAdjust the value for tbl_order.is_adjust
     *
     * @mbggenerated
     */
    public void setIsAdjust(Integer isAdjust) {
        this.isAdjust = isAdjust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.is_dissent
     *
     * @return the value of tbl_order.is_dissent
     *
     * @mbggenerated
     */
    public Integer getIsDissent() {
        return isDissent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.is_dissent
     *
     * @param isDissent the value for tbl_order.is_dissent
     *
     * @mbggenerated
     */
    public void setIsDissent(Integer isDissent) {
        this.isDissent = isDissent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.is_manual
     *
     * @return the value of tbl_order.is_manual
     *
     * @mbggenerated
     */
    public Integer getIsManual() {
        return isManual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.is_manual
     *
     * @param isManual the value for tbl_order.is_manual
     *
     * @mbggenerated
     */
    public void setIsManual(Integer isManual) {
        this.isManual = isManual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.is_following
     *
     * @return the value of tbl_order.is_following
     *
     * @mbggenerated
     */
    public Integer getIsFollowing() {
        return isFollowing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.is_following
     *
     * @param isFollowing the value for tbl_order.is_following
     *
     * @mbggenerated
     */
    public void setIsFollowing(Integer isFollowing) {
        this.isFollowing = isFollowing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.is_fake_success
     *
     * @return the value of tbl_order.is_fake_success
     *
     * @mbggenerated
     */
    public Integer getIsFakeSuccess() {
        return isFakeSuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.is_fake_success
     *
     * @param isFakeSuccess the value for tbl_order.is_fake_success
     *
     * @mbggenerated
     */
    public void setIsFakeSuccess(Integer isFakeSuccess) {
        this.isFakeSuccess = isFakeSuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.memo
     *
     * @return the value of tbl_order.memo
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.memo
     *
     * @param memo the value for tbl_order.memo
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.is_use_risk
     *
     * @return the value of tbl_order.is_use_risk
     *
     * @mbggenerated
     */
    public Integer getIsUseRisk() {
        return isUseRisk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.is_use_risk
     *
     * @param isUseRisk the value for tbl_order.is_use_risk
     *
     * @mbggenerated
     */
    public void setIsUseRisk(Integer isUseRisk) {
        this.isUseRisk = isUseRisk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.create_time
     *
     * @return the value of tbl_order.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.create_time
     *
     * @param createTime the value for tbl_order.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.update_time
     *
     * @return the value of tbl_order.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.update_time
     *
     * @param updateTime the value for tbl_order.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}