package com.online.taxi.entity;

public class OrderPoints {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_points.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_points.driver_id
     *
     * @mbggenerated
     */
    private Integer driverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_points.car_id
     *
     * @mbggenerated
     */
    private Integer carId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_points.order_id
     *
     * @mbggenerated
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_points.points
     *
     * @mbggenerated
     */
    private String points;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_points.id
     *
     * @return the value of tbl_order_points.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_points.id
     *
     * @param id the value for tbl_order_points.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_points.driver_id
     *
     * @return the value of tbl_order_points.driver_id
     *
     * @mbggenerated
     */
    public Integer getDriverId() {
        return driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_points.driver_id
     *
     * @param driverId the value for tbl_order_points.driver_id
     *
     * @mbggenerated
     */
    public void setDriverId(Integer driverId) {
        this.driverId = driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_points.car_id
     *
     * @return the value of tbl_order_points.car_id
     *
     * @mbggenerated
     */
    public Integer getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_points.car_id
     *
     * @param carId the value for tbl_order_points.car_id
     *
     * @mbggenerated
     */
    public void setCarId(Integer carId) {
        this.carId = carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_points.order_id
     *
     * @return the value of tbl_order_points.order_id
     *
     * @mbggenerated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_points.order_id
     *
     * @param orderId the value for tbl_order_points.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_points.points
     *
     * @return the value of tbl_order_points.points
     *
     * @mbggenerated
     */
    public String getPoints() {
        return points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_points.points
     *
     * @param points the value for tbl_order_points.points
     *
     * @mbggenerated
     */
    public void setPoints(String points) {
        this.points = points == null ? null : points.trim();
    }
}