package com.online.taxi.entity;

import java.math.BigDecimal;
import java.util.Date;

public class OrderRulePrice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_rule_price.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_rule_price.order_id
     *
     * @mbggenerated
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_rule_price.category
     *
     * @mbggenerated
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_rule_price.total_price
     *
     * @mbggenerated
     */
    private BigDecimal totalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_rule_price.total_distance
     *
     * @mbggenerated
     */
    private Double totalDistance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_rule_price.total_time
     *
     * @mbggenerated
     */
    private Double totalTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_rule_price.city_code
     *
     * @mbggenerated
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_rule_price.city_name
     *
     * @mbggenerated
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_rule_price.service_type_id
     *
     * @mbggenerated
     */
    private Integer serviceTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_rule_price.service_type_name
     *
     * @mbggenerated
     */
    private String serviceTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_rule_price.channel_id
     *
     * @mbggenerated
     */
    private Integer channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_rule_price.channel_name
     *
     * @mbggenerated
     */
    private String channelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_rule_price.car_level_id
     *
     * @mbggenerated
     */
    private Integer carLevelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_rule_price.car_level_name
     *
     * @mbggenerated
     */
    private String carLevelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_rule_price.base_price
     *
     * @mbggenerated
     */
    private BigDecimal basePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_rule_price.base_kilo
     *
     * @mbggenerated
     */
    private Double baseKilo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_rule_price.base_minute
     *
     * @mbggenerated
     */
    private Double baseMinute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_rule_price.lowest_price
     *
     * @mbggenerated
     */
    private BigDecimal lowestPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_rule_price.night_start
     *
     * @mbggenerated
     */
    private Date nightStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_rule_price.night_end
     *
     * @mbggenerated
     */
    private Date nightEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_rule_price.night_per_kilo_price
     *
     * @mbggenerated
     */
    private BigDecimal nightPerKiloPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_rule_price.night_per_minute_price
     *
     * @mbggenerated
     */
    private BigDecimal nightPerMinutePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_rule_price.night_distance
     *
     * @mbggenerated
     */
    private Double nightDistance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_rule_price.night_time
     *
     * @mbggenerated
     */
    private Double nightTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_rule_price.night_price
     *
     * @mbggenerated
     */
    private BigDecimal nightPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_rule_price.beyond_start_kilo
     *
     * @mbggenerated
     */
    private Double beyondStartKilo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_rule_price.beyond_per_kilo_price
     *
     * @mbggenerated
     */
    private BigDecimal beyondPerKiloPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_rule_price.beyond_distance
     *
     * @mbggenerated
     */
    private Double beyondDistance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_rule_price.beyond_price
     *
     * @mbggenerated
     */
    private BigDecimal beyondPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_rule_price.per_kilo_price
     *
     * @mbggenerated
     */
    private BigDecimal perKiloPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_rule_price.path
     *
     * @mbggenerated
     */
    private Double path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_rule_price.path_price
     *
     * @mbggenerated
     */
    private BigDecimal pathPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_rule_price.per_minute_price
     *
     * @mbggenerated
     */
    private BigDecimal perMinutePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_rule_price.duration
     *
     * @mbggenerated
     */
    private Double duration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_rule_price.duration_price
     *
     * @mbggenerated
     */
    private BigDecimal durationPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_rule_price.rest_duration
     *
     * @mbggenerated
     */
    private Double restDuration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_rule_price.rest_duration_price
     *
     * @mbggenerated
     */
    private BigDecimal restDurationPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_rule_price.rest_distance
     *
     * @mbggenerated
     */
    private Double restDistance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_rule_price.rest_distance_price
     *
     * @mbggenerated
     */
    private BigDecimal restDistancePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_rule_price.road_price
     *
     * @mbggenerated
     */
    private BigDecimal roadPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_rule_price.parking_price
     *
     * @mbggenerated
     */
    private BigDecimal parkingPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_rule_price.other_price
     *
     * @mbggenerated
     */
    private BigDecimal otherPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_rule_price.dynamic_discount_rate
     *
     * @mbggenerated
     */
    private Double dynamicDiscountRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_rule_price.dynamic_discount
     *
     * @mbggenerated
     */
    private BigDecimal dynamicDiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_rule_price.supplement_price
     *
     * @mbggenerated
     */
    private BigDecimal supplementPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_rule_price.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_rule_price.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_rule_price.id
     *
     * @return the value of tbl_order_rule_price.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_rule_price.id
     *
     * @param id the value for tbl_order_rule_price.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_rule_price.order_id
     *
     * @return the value of tbl_order_rule_price.order_id
     *
     * @mbggenerated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_rule_price.order_id
     *
     * @param orderId the value for tbl_order_rule_price.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_rule_price.category
     *
     * @return the value of tbl_order_rule_price.category
     *
     * @mbggenerated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_rule_price.category
     *
     * @param category the value for tbl_order_rule_price.category
     *
     * @mbggenerated
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_rule_price.total_price
     *
     * @return the value of tbl_order_rule_price.total_price
     *
     * @mbggenerated
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_rule_price.total_price
     *
     * @param totalPrice the value for tbl_order_rule_price.total_price
     *
     * @mbggenerated
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_rule_price.total_distance
     *
     * @return the value of tbl_order_rule_price.total_distance
     *
     * @mbggenerated
     */
    public Double getTotalDistance() {
        return totalDistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_rule_price.total_distance
     *
     * @param totalDistance the value for tbl_order_rule_price.total_distance
     *
     * @mbggenerated
     */
    public void setTotalDistance(Double totalDistance) {
        this.totalDistance = totalDistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_rule_price.total_time
     *
     * @return the value of tbl_order_rule_price.total_time
     *
     * @mbggenerated
     */
    public Double getTotalTime() {
        return totalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_rule_price.total_time
     *
     * @param totalTime the value for tbl_order_rule_price.total_time
     *
     * @mbggenerated
     */
    public void setTotalTime(Double totalTime) {
        this.totalTime = totalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_rule_price.city_code
     *
     * @return the value of tbl_order_rule_price.city_code
     *
     * @mbggenerated
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_rule_price.city_code
     *
     * @param cityCode the value for tbl_order_rule_price.city_code
     *
     * @mbggenerated
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_rule_price.city_name
     *
     * @return the value of tbl_order_rule_price.city_name
     *
     * @mbggenerated
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_rule_price.city_name
     *
     * @param cityName the value for tbl_order_rule_price.city_name
     *
     * @mbggenerated
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_rule_price.service_type_id
     *
     * @return the value of tbl_order_rule_price.service_type_id
     *
     * @mbggenerated
     */
    public Integer getServiceTypeId() {
        return serviceTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_rule_price.service_type_id
     *
     * @param serviceTypeId the value for tbl_order_rule_price.service_type_id
     *
     * @mbggenerated
     */
    public void setServiceTypeId(Integer serviceTypeId) {
        this.serviceTypeId = serviceTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_rule_price.service_type_name
     *
     * @return the value of tbl_order_rule_price.service_type_name
     *
     * @mbggenerated
     */
    public String getServiceTypeName() {
        return serviceTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_rule_price.service_type_name
     *
     * @param serviceTypeName the value for tbl_order_rule_price.service_type_name
     *
     * @mbggenerated
     */
    public void setServiceTypeName(String serviceTypeName) {
        this.serviceTypeName = serviceTypeName == null ? null : serviceTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_rule_price.channel_id
     *
     * @return the value of tbl_order_rule_price.channel_id
     *
     * @mbggenerated
     */
    public Integer getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_rule_price.channel_id
     *
     * @param channelId the value for tbl_order_rule_price.channel_id
     *
     * @mbggenerated
     */
    public void setChannelId(Integer channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_rule_price.channel_name
     *
     * @return the value of tbl_order_rule_price.channel_name
     *
     * @mbggenerated
     */
    public String getChannelName() {
        return channelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_rule_price.channel_name
     *
     * @param channelName the value for tbl_order_rule_price.channel_name
     *
     * @mbggenerated
     */
    public void setChannelName(String channelName) {
        this.channelName = channelName == null ? null : channelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_rule_price.car_level_id
     *
     * @return the value of tbl_order_rule_price.car_level_id
     *
     * @mbggenerated
     */
    public Integer getCarLevelId() {
        return carLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_rule_price.car_level_id
     *
     * @param carLevelId the value for tbl_order_rule_price.car_level_id
     *
     * @mbggenerated
     */
    public void setCarLevelId(Integer carLevelId) {
        this.carLevelId = carLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_rule_price.car_level_name
     *
     * @return the value of tbl_order_rule_price.car_level_name
     *
     * @mbggenerated
     */
    public String getCarLevelName() {
        return carLevelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_rule_price.car_level_name
     *
     * @param carLevelName the value for tbl_order_rule_price.car_level_name
     *
     * @mbggenerated
     */
    public void setCarLevelName(String carLevelName) {
        this.carLevelName = carLevelName == null ? null : carLevelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_rule_price.base_price
     *
     * @return the value of tbl_order_rule_price.base_price
     *
     * @mbggenerated
     */
    public BigDecimal getBasePrice() {
        return basePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_rule_price.base_price
     *
     * @param basePrice the value for tbl_order_rule_price.base_price
     *
     * @mbggenerated
     */
    public void setBasePrice(BigDecimal basePrice) {
        this.basePrice = basePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_rule_price.base_kilo
     *
     * @return the value of tbl_order_rule_price.base_kilo
     *
     * @mbggenerated
     */
    public Double getBaseKilo() {
        return baseKilo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_rule_price.base_kilo
     *
     * @param baseKilo the value for tbl_order_rule_price.base_kilo
     *
     * @mbggenerated
     */
    public void setBaseKilo(Double baseKilo) {
        this.baseKilo = baseKilo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_rule_price.base_minute
     *
     * @return the value of tbl_order_rule_price.base_minute
     *
     * @mbggenerated
     */
    public Double getBaseMinute() {
        return baseMinute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_rule_price.base_minute
     *
     * @param baseMinute the value for tbl_order_rule_price.base_minute
     *
     * @mbggenerated
     */
    public void setBaseMinute(Double baseMinute) {
        this.baseMinute = baseMinute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_rule_price.lowest_price
     *
     * @return the value of tbl_order_rule_price.lowest_price
     *
     * @mbggenerated
     */
    public BigDecimal getLowestPrice() {
        return lowestPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_rule_price.lowest_price
     *
     * @param lowestPrice the value for tbl_order_rule_price.lowest_price
     *
     * @mbggenerated
     */
    public void setLowestPrice(BigDecimal lowestPrice) {
        this.lowestPrice = lowestPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_rule_price.night_start
     *
     * @return the value of tbl_order_rule_price.night_start
     *
     * @mbggenerated
     */
    public Date getNightStart() {
        return nightStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_rule_price.night_start
     *
     * @param nightStart the value for tbl_order_rule_price.night_start
     *
     * @mbggenerated
     */
    public void setNightStart(Date nightStart) {
        this.nightStart = nightStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_rule_price.night_end
     *
     * @return the value of tbl_order_rule_price.night_end
     *
     * @mbggenerated
     */
    public Date getNightEnd() {
        return nightEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_rule_price.night_end
     *
     * @param nightEnd the value for tbl_order_rule_price.night_end
     *
     * @mbggenerated
     */
    public void setNightEnd(Date nightEnd) {
        this.nightEnd = nightEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_rule_price.night_per_kilo_price
     *
     * @return the value of tbl_order_rule_price.night_per_kilo_price
     *
     * @mbggenerated
     */
    public BigDecimal getNightPerKiloPrice() {
        return nightPerKiloPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_rule_price.night_per_kilo_price
     *
     * @param nightPerKiloPrice the value for tbl_order_rule_price.night_per_kilo_price
     *
     * @mbggenerated
     */
    public void setNightPerKiloPrice(BigDecimal nightPerKiloPrice) {
        this.nightPerKiloPrice = nightPerKiloPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_rule_price.night_per_minute_price
     *
     * @return the value of tbl_order_rule_price.night_per_minute_price
     *
     * @mbggenerated
     */
    public BigDecimal getNightPerMinutePrice() {
        return nightPerMinutePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_rule_price.night_per_minute_price
     *
     * @param nightPerMinutePrice the value for tbl_order_rule_price.night_per_minute_price
     *
     * @mbggenerated
     */
    public void setNightPerMinutePrice(BigDecimal nightPerMinutePrice) {
        this.nightPerMinutePrice = nightPerMinutePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_rule_price.night_distance
     *
     * @return the value of tbl_order_rule_price.night_distance
     *
     * @mbggenerated
     */
    public Double getNightDistance() {
        return nightDistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_rule_price.night_distance
     *
     * @param nightDistance the value for tbl_order_rule_price.night_distance
     *
     * @mbggenerated
     */
    public void setNightDistance(Double nightDistance) {
        this.nightDistance = nightDistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_rule_price.night_time
     *
     * @return the value of tbl_order_rule_price.night_time
     *
     * @mbggenerated
     */
    public Double getNightTime() {
        return nightTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_rule_price.night_time
     *
     * @param nightTime the value for tbl_order_rule_price.night_time
     *
     * @mbggenerated
     */
    public void setNightTime(Double nightTime) {
        this.nightTime = nightTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_rule_price.night_price
     *
     * @return the value of tbl_order_rule_price.night_price
     *
     * @mbggenerated
     */
    public BigDecimal getNightPrice() {
        return nightPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_rule_price.night_price
     *
     * @param nightPrice the value for tbl_order_rule_price.night_price
     *
     * @mbggenerated
     */
    public void setNightPrice(BigDecimal nightPrice) {
        this.nightPrice = nightPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_rule_price.beyond_start_kilo
     *
     * @return the value of tbl_order_rule_price.beyond_start_kilo
     *
     * @mbggenerated
     */
    public Double getBeyondStartKilo() {
        return beyondStartKilo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_rule_price.beyond_start_kilo
     *
     * @param beyondStartKilo the value for tbl_order_rule_price.beyond_start_kilo
     *
     * @mbggenerated
     */
    public void setBeyondStartKilo(Double beyondStartKilo) {
        this.beyondStartKilo = beyondStartKilo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_rule_price.beyond_per_kilo_price
     *
     * @return the value of tbl_order_rule_price.beyond_per_kilo_price
     *
     * @mbggenerated
     */
    public BigDecimal getBeyondPerKiloPrice() {
        return beyondPerKiloPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_rule_price.beyond_per_kilo_price
     *
     * @param beyondPerKiloPrice the value for tbl_order_rule_price.beyond_per_kilo_price
     *
     * @mbggenerated
     */
    public void setBeyondPerKiloPrice(BigDecimal beyondPerKiloPrice) {
        this.beyondPerKiloPrice = beyondPerKiloPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_rule_price.beyond_distance
     *
     * @return the value of tbl_order_rule_price.beyond_distance
     *
     * @mbggenerated
     */
    public Double getBeyondDistance() {
        return beyondDistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_rule_price.beyond_distance
     *
     * @param beyondDistance the value for tbl_order_rule_price.beyond_distance
     *
     * @mbggenerated
     */
    public void setBeyondDistance(Double beyondDistance) {
        this.beyondDistance = beyondDistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_rule_price.beyond_price
     *
     * @return the value of tbl_order_rule_price.beyond_price
     *
     * @mbggenerated
     */
    public BigDecimal getBeyondPrice() {
        return beyondPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_rule_price.beyond_price
     *
     * @param beyondPrice the value for tbl_order_rule_price.beyond_price
     *
     * @mbggenerated
     */
    public void setBeyondPrice(BigDecimal beyondPrice) {
        this.beyondPrice = beyondPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_rule_price.per_kilo_price
     *
     * @return the value of tbl_order_rule_price.per_kilo_price
     *
     * @mbggenerated
     */
    public BigDecimal getPerKiloPrice() {
        return perKiloPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_rule_price.per_kilo_price
     *
     * @param perKiloPrice the value for tbl_order_rule_price.per_kilo_price
     *
     * @mbggenerated
     */
    public void setPerKiloPrice(BigDecimal perKiloPrice) {
        this.perKiloPrice = perKiloPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_rule_price.path
     *
     * @return the value of tbl_order_rule_price.path
     *
     * @mbggenerated
     */
    public Double getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_rule_price.path
     *
     * @param path the value for tbl_order_rule_price.path
     *
     * @mbggenerated
     */
    public void setPath(Double path) {
        this.path = path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_rule_price.path_price
     *
     * @return the value of tbl_order_rule_price.path_price
     *
     * @mbggenerated
     */
    public BigDecimal getPathPrice() {
        return pathPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_rule_price.path_price
     *
     * @param pathPrice the value for tbl_order_rule_price.path_price
     *
     * @mbggenerated
     */
    public void setPathPrice(BigDecimal pathPrice) {
        this.pathPrice = pathPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_rule_price.per_minute_price
     *
     * @return the value of tbl_order_rule_price.per_minute_price
     *
     * @mbggenerated
     */
    public BigDecimal getPerMinutePrice() {
        return perMinutePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_rule_price.per_minute_price
     *
     * @param perMinutePrice the value for tbl_order_rule_price.per_minute_price
     *
     * @mbggenerated
     */
    public void setPerMinutePrice(BigDecimal perMinutePrice) {
        this.perMinutePrice = perMinutePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_rule_price.duration
     *
     * @return the value of tbl_order_rule_price.duration
     *
     * @mbggenerated
     */
    public Double getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_rule_price.duration
     *
     * @param duration the value for tbl_order_rule_price.duration
     *
     * @mbggenerated
     */
    public void setDuration(Double duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_rule_price.duration_price
     *
     * @return the value of tbl_order_rule_price.duration_price
     *
     * @mbggenerated
     */
    public BigDecimal getDurationPrice() {
        return durationPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_rule_price.duration_price
     *
     * @param durationPrice the value for tbl_order_rule_price.duration_price
     *
     * @mbggenerated
     */
    public void setDurationPrice(BigDecimal durationPrice) {
        this.durationPrice = durationPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_rule_price.rest_duration
     *
     * @return the value of tbl_order_rule_price.rest_duration
     *
     * @mbggenerated
     */
    public Double getRestDuration() {
        return restDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_rule_price.rest_duration
     *
     * @param restDuration the value for tbl_order_rule_price.rest_duration
     *
     * @mbggenerated
     */
    public void setRestDuration(Double restDuration) {
        this.restDuration = restDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_rule_price.rest_duration_price
     *
     * @return the value of tbl_order_rule_price.rest_duration_price
     *
     * @mbggenerated
     */
    public BigDecimal getRestDurationPrice() {
        return restDurationPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_rule_price.rest_duration_price
     *
     * @param restDurationPrice the value for tbl_order_rule_price.rest_duration_price
     *
     * @mbggenerated
     */
    public void setRestDurationPrice(BigDecimal restDurationPrice) {
        this.restDurationPrice = restDurationPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_rule_price.rest_distance
     *
     * @return the value of tbl_order_rule_price.rest_distance
     *
     * @mbggenerated
     */
    public Double getRestDistance() {
        return restDistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_rule_price.rest_distance
     *
     * @param restDistance the value for tbl_order_rule_price.rest_distance
     *
     * @mbggenerated
     */
    public void setRestDistance(Double restDistance) {
        this.restDistance = restDistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_rule_price.rest_distance_price
     *
     * @return the value of tbl_order_rule_price.rest_distance_price
     *
     * @mbggenerated
     */
    public BigDecimal getRestDistancePrice() {
        return restDistancePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_rule_price.rest_distance_price
     *
     * @param restDistancePrice the value for tbl_order_rule_price.rest_distance_price
     *
     * @mbggenerated
     */
    public void setRestDistancePrice(BigDecimal restDistancePrice) {
        this.restDistancePrice = restDistancePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_rule_price.road_price
     *
     * @return the value of tbl_order_rule_price.road_price
     *
     * @mbggenerated
     */
    public BigDecimal getRoadPrice() {
        return roadPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_rule_price.road_price
     *
     * @param roadPrice the value for tbl_order_rule_price.road_price
     *
     * @mbggenerated
     */
    public void setRoadPrice(BigDecimal roadPrice) {
        this.roadPrice = roadPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_rule_price.parking_price
     *
     * @return the value of tbl_order_rule_price.parking_price
     *
     * @mbggenerated
     */
    public BigDecimal getParkingPrice() {
        return parkingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_rule_price.parking_price
     *
     * @param parkingPrice the value for tbl_order_rule_price.parking_price
     *
     * @mbggenerated
     */
    public void setParkingPrice(BigDecimal parkingPrice) {
        this.parkingPrice = parkingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_rule_price.other_price
     *
     * @return the value of tbl_order_rule_price.other_price
     *
     * @mbggenerated
     */
    public BigDecimal getOtherPrice() {
        return otherPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_rule_price.other_price
     *
     * @param otherPrice the value for tbl_order_rule_price.other_price
     *
     * @mbggenerated
     */
    public void setOtherPrice(BigDecimal otherPrice) {
        this.otherPrice = otherPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_rule_price.dynamic_discount_rate
     *
     * @return the value of tbl_order_rule_price.dynamic_discount_rate
     *
     * @mbggenerated
     */
    public Double getDynamicDiscountRate() {
        return dynamicDiscountRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_rule_price.dynamic_discount_rate
     *
     * @param dynamicDiscountRate the value for tbl_order_rule_price.dynamic_discount_rate
     *
     * @mbggenerated
     */
    public void setDynamicDiscountRate(Double dynamicDiscountRate) {
        this.dynamicDiscountRate = dynamicDiscountRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_rule_price.dynamic_discount
     *
     * @return the value of tbl_order_rule_price.dynamic_discount
     *
     * @mbggenerated
     */
    public BigDecimal getDynamicDiscount() {
        return dynamicDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_rule_price.dynamic_discount
     *
     * @param dynamicDiscount the value for tbl_order_rule_price.dynamic_discount
     *
     * @mbggenerated
     */
    public void setDynamicDiscount(BigDecimal dynamicDiscount) {
        this.dynamicDiscount = dynamicDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_rule_price.supplement_price
     *
     * @return the value of tbl_order_rule_price.supplement_price
     *
     * @mbggenerated
     */
    public BigDecimal getSupplementPrice() {
        return supplementPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_rule_price.supplement_price
     *
     * @param supplementPrice the value for tbl_order_rule_price.supplement_price
     *
     * @mbggenerated
     */
    public void setSupplementPrice(BigDecimal supplementPrice) {
        this.supplementPrice = supplementPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_rule_price.create_time
     *
     * @return the value of tbl_order_rule_price.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_rule_price.create_time
     *
     * @param createTime the value for tbl_order_rule_price.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_rule_price.update_time
     *
     * @return the value of tbl_order_rule_price.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_rule_price.update_time
     *
     * @param updateTime the value for tbl_order_rule_price.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}