package com.online.taxi.entity;

import java.util.Date;

public class PassengerRegisterSource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_register_source.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_register_source.passenger_info_id
     *
     * @mbggenerated
     */
    private Integer passengerInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_register_source.register_source
     *
     * @mbggenerated
     */
    private String registerSource;

    private String marketChannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_register_source.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_register_source.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    public String getMarketChannel() {
        return marketChannel;
    }

    public void setMarketChannel(String marketChannel) {
        this.marketChannel = marketChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_register_source.id
     *
     * @return the value of tbl_passenger_register_source.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_passenger_register_source.id
     *
     * @param id the value for tbl_passenger_register_source.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_register_source.passenger_info_id
     *
     * @return the value of tbl_passenger_register_source.passenger_info_id
     *
     * @mbggenerated
     */
    public Integer getPassengerInfoId() {
        return passengerInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_passenger_register_source.passenger_info_id
     *
     * @param passengerInfoId the value for tbl_passenger_register_source.passenger_info_id
     *
     * @mbggenerated
     */
    public void setPassengerInfoId(Integer passengerInfoId) {
        this.passengerInfoId = passengerInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_register_source.register_source
     *
     * @return the value of tbl_passenger_register_source.register_source
     *
     * @mbggenerated
     */
    public String getRegisterSource() {
        return registerSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_passenger_register_source.register_source
     *
     * @param registerSource the value for tbl_passenger_register_source.register_source
     *
     * @mbggenerated
     */
    public void setRegisterSource(String registerSource) {
        this.registerSource = registerSource == null ? null : registerSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_register_source.create_time
     *
     * @return the value of tbl_passenger_register_source.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_passenger_register_source.create_time
     *
     * @param createTime the value for tbl_passenger_register_source.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_register_source.update_time
     *
     * @return the value of tbl_passenger_register_source.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_passenger_register_source.update_time
     *
     * @param updateTime the value for tbl_passenger_register_source.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}