package com.online.taxi.entity;

import java.math.BigDecimal;
import java.util.Date;


/**
 */
public class PassengerInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_info.phone
     *
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_info.educatioan
     *
     */
    private String educatioan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_info.birthday
     *
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_info.passenger_name
     *
     * @mbggenerated
     */
    private String passengerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_info.register_time
     *
     * @mbggenerated
     */
    private Date registerTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_info.balance
     *
     * @mbggenerated
     */
    private BigDecimal balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_info.gender
     *
     * @mbggenerated
     */
    private Byte gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_info.head_img
     *
     * @mbggenerated
     */
    private String headImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_info.passenger_type
     *
     * @mbggenerated
     */
    private Byte passengerType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_info.user_level
     *
     * @mbggenerated
     */
    private Byte userLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_info.register_type
     *
     * @mbggenerated
     */
    private Short registerType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_info.last_login_time
     *
     * @mbggenerated
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_info.last_login_method
     *
     * @mbggenerated
     */
    private Byte lastLoginMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_info.last_login_screen_time
     *
     * @mbggenerated
     */
    private Date lastLoginScreenTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_info.last_login_screen_method
     *
     * @mbggenerated
     */
    private String lastLoginScreenMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_info.last_order_time
     *
     * @mbggenerated
     */
    private Date lastOrderTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_info.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    private Integer isContact;

    private Integer isShare;

    private String sharingTime;

    public Integer getIsShare() {
        return isShare;
    }

    public void setIsShare(Integer isShare) {
        this.isShare = isShare;
    }

    public String getSharingTime() {
        return sharingTime;
    }

    public void setSharingTime(String sharingTime) {
        this.sharingTime = sharingTime;
    }

    public Integer getIsContact() {
        return isContact;
    }

    public void setIsContact(Integer isContact) {
        this.isContact = isContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_info.id
     *
     * @return the value of tbl_passenger_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_passenger_info.id
     *
     * @param id the value for tbl_passenger_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_info.phone
     *
     * @return the value of tbl_passenger_info.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_passenger_info.phone
     *
     * @param phone the value for tbl_passenger_info.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_info.educatioan
     *
     * @return the value of tbl_passenger_info.educatioan
     *
     * @mbggenerated
     */
    public String getEducatioan() {
        return educatioan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_passenger_info.educatioan
     *
     * @param educatioan the value for tbl_passenger_info.educatioan
     *
     * @mbggenerated
     */
    public void setEducatioan(String educatioan) {
        this.educatioan = educatioan == null ? null : educatioan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_info.birthday
     *
     * @return the value of tbl_passenger_info.birthday
     *
     * @mbggenerated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_passenger_info.birthday
     *
     * @param birthday the value for tbl_passenger_info.birthday
     *
     * @mbggenerated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_info.passenger_name
     *
     * @return the value of tbl_passenger_info.passenger_name
     *
     * @mbggenerated
     */
    public String getPassengerName() {
        return passengerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_passenger_info.passenger_name
     *
     * @param passengerName the value for tbl_passenger_info.passenger_name
     *
     * @mbggenerated
     */
    public void setPassengerName(String passengerName) {
        this.passengerName = passengerName == null ? null : passengerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_info.register_time
     *
     * @return the value of tbl_passenger_info.register_time
     *
     * @mbggenerated
     */
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_passenger_info.register_time
     *
     * @param registerTime the value for tbl_passenger_info.register_time
     *
     * @mbggenerated
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_info.balance
     *
     * @return the value of tbl_passenger_info.balance
     *
     * @mbggenerated
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_passenger_info.balance
     *
     * @param balance the value for tbl_passenger_info.balance
     *
     * @mbggenerated
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_info.gender
     *
     * @return the value of tbl_passenger_info.gender
     *
     * @mbggenerated
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_passenger_info.gender
     *
     * @param gender the value for tbl_passenger_info.gender
     *
     * @mbggenerated
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_info.head_img
     *
     * @return the value of tbl_passenger_info.head_img
     *
     * @mbggenerated
     */
    public String getHeadImg() {
        return headImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_passenger_info.head_img
     *
     * @param headImg the value for tbl_passenger_info.head_img
     *
     * @mbggenerated
     */
    public void setHeadImg(String headImg) {
        this.headImg = headImg == null ? null : headImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_info.passenger_type
     *
     * @return the value of tbl_passenger_info.passenger_type
     *
     * @mbggenerated
     */
    public Byte getPassengerType() {
        return passengerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_passenger_info.passenger_type
     *
     * @param passengerType the value for tbl_passenger_info.passenger_type
     *
     * @mbggenerated
     */
    public void setPassengerType(Byte passengerType) {
        this.passengerType = passengerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_info.user_level
     *
     * @return the value of tbl_passenger_info.user_level
     *
     * @mbggenerated
     */
    public Byte getUserLevel() {
        return userLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_passenger_info.user_level
     *
     * @param userLevel the value for tbl_passenger_info.user_level
     *
     * @mbggenerated
     */
    public void setUserLevel(Byte userLevel) {
        this.userLevel = userLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_info.register_type
     *
     * @return the value of tbl_passenger_info.register_type
     *
     * @mbggenerated
     */
    public Short getRegisterType() {
        return registerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_passenger_info.register_type
     *
     * @param registerType the value for tbl_passenger_info.register_type
     *
     * @mbggenerated
     */
    public void setRegisterType(Short registerType) {
        this.registerType = registerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_info.last_login_time
     *
     * @return the value of tbl_passenger_info.last_login_time
     *
     * @mbggenerated
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_passenger_info.last_login_time
     *
     * @param lastLoginTime the value for tbl_passenger_info.last_login_time
     *
     * @mbggenerated
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_info.last_login_method
     *
     * @return the value of tbl_passenger_info.last_login_method
     *
     * @mbggenerated
     */
    public Byte getLastLoginMethod() {
        return lastLoginMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_passenger_info.last_login_method
     *
     * @param lastLoginMethod the value for tbl_passenger_info.last_login_method
     *
     * @mbggenerated
     */
    public void setLastLoginMethod(Byte lastLoginMethod) {
        this.lastLoginMethod = lastLoginMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_info.last_login_screen_time
     *
     * @return the value of tbl_passenger_info.last_login_screen_time
     *
     * @mbggenerated
     */
    public Date getLastLoginScreenTime() {
        return lastLoginScreenTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_passenger_info.last_login_screen_time
     *
     * @param lastLoginScreenTime the value for tbl_passenger_info.last_login_screen_time
     *
     * @mbggenerated
     */
    public void setLastLoginScreenTime(Date lastLoginScreenTime) {
        this.lastLoginScreenTime = lastLoginScreenTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_info.last_login_screen_method
     *
     * @return the value of tbl_passenger_info.last_login_screen_method
     *
     * @mbggenerated
     */
    public String getLastLoginScreenMethod() {
        return lastLoginScreenMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_passenger_info.last_login_screen_method
     *
     * @param lastLoginScreenMethod the value for tbl_passenger_info.last_login_screen_method
     *
     * @mbggenerated
     */
    public void setLastLoginScreenMethod(String lastLoginScreenMethod) {
        this.lastLoginScreenMethod = lastLoginScreenMethod == null ? null : lastLoginScreenMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_info.last_order_time
     *
     * @return the value of tbl_passenger_info.last_order_time
     *
     * @mbggenerated
     */
    public Date getLastOrderTime() {
        return lastOrderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_passenger_info.last_order_time
     *
     * @param lastOrderTime the value for tbl_passenger_info.last_order_time
     *
     * @mbggenerated
     */
    public void setLastOrderTime(Date lastOrderTime) {
        this.lastOrderTime = lastOrderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_info.create_time
     *
     * @return the value of tbl_passenger_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_passenger_info.create_time
     *
     * @param createTime the value for tbl_passenger_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_info.update_time
     *
     * @return the value of tbl_passenger_info.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_passenger_info.update_time
     *
     * @param updateTime the value for tbl_passenger_info.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}
