package com.online.taxi.entity;

import java.math.BigDecimal;

public class PassengerStatics {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_statics.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_statics.passenger_info_id
     *
     * @mbggenerated
     */
    private Integer passengerInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_statics.total_distance
     *
     * @mbggenerated
     */
    private BigDecimal totalDistance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_statics.month_distance
     *
     * @mbggenerated
     */
    private BigDecimal monthDistance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_statics.total_charge
     *
     * @mbggenerated
     */
    private BigDecimal totalCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_statics.total_refund
     *
     * @mbggenerated
     */
    private BigDecimal totalRefund;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_statics.total_order_pay
     *
     * @mbggenerated
     */
    private BigDecimal totalOrderPay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_statics.month_order_pay
     *
     * @mbggenerated
     */
    private BigDecimal monthOrderPay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_statics.total_invoice
     *
     * @mbggenerated
     */
    private BigDecimal totalInvoice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_statics.can_invoice
     *
     * @mbggenerated
     */
    private BigDecimal canInvoice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_statics.id
     *
     * @return the value of tbl_passenger_statics.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_passenger_statics.id
     *
     * @param id the value for tbl_passenger_statics.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_statics.passenger_info_id
     *
     * @return the value of tbl_passenger_statics.passenger_info_id
     *
     * @mbggenerated
     */
    public Integer getPassengerInfoId() {
        return passengerInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_passenger_statics.passenger_info_id
     *
     * @param passengerInfoId the value for tbl_passenger_statics.passenger_info_id
     *
     * @mbggenerated
     */
    public void setPassengerInfoId(Integer passengerInfoId) {
        this.passengerInfoId = passengerInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_statics.total_distance
     *
     * @return the value of tbl_passenger_statics.total_distance
     *
     * @mbggenerated
     */
    public BigDecimal getTotalDistance() {
        return totalDistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_passenger_statics.total_distance
     *
     * @param totalDistance the value for tbl_passenger_statics.total_distance
     *
     * @mbggenerated
     */
    public void setTotalDistance(BigDecimal totalDistance) {
        this.totalDistance = totalDistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_statics.month_distance
     *
     * @return the value of tbl_passenger_statics.month_distance
     *
     * @mbggenerated
     */
    public BigDecimal getMonthDistance() {
        return monthDistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_passenger_statics.month_distance
     *
     * @param monthDistance the value for tbl_passenger_statics.month_distance
     *
     * @mbggenerated
     */
    public void setMonthDistance(BigDecimal monthDistance) {
        this.monthDistance = monthDistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_statics.total_charge
     *
     * @return the value of tbl_passenger_statics.total_charge
     *
     * @mbggenerated
     */
    public BigDecimal getTotalCharge() {
        return totalCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_passenger_statics.total_charge
     *
     * @param totalCharge the value for tbl_passenger_statics.total_charge
     *
     * @mbggenerated
     */
    public void setTotalCharge(BigDecimal totalCharge) {
        this.totalCharge = totalCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_statics.total_refund
     *
     * @return the value of tbl_passenger_statics.total_refund
     *
     * @mbggenerated
     */
    public BigDecimal getTotalRefund() {
        return totalRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_passenger_statics.total_refund
     *
     * @param totalRefund the value for tbl_passenger_statics.total_refund
     *
     * @mbggenerated
     */
    public void setTotalRefund(BigDecimal totalRefund) {
        this.totalRefund = totalRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_statics.total_order_pay
     *
     * @return the value of tbl_passenger_statics.total_order_pay
     *
     * @mbggenerated
     */
    public BigDecimal getTotalOrderPay() {
        return totalOrderPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_passenger_statics.total_order_pay
     *
     * @param totalOrderPay the value for tbl_passenger_statics.total_order_pay
     *
     * @mbggenerated
     */
    public void setTotalOrderPay(BigDecimal totalOrderPay) {
        this.totalOrderPay = totalOrderPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_statics.month_order_pay
     *
     * @return the value of tbl_passenger_statics.month_order_pay
     *
     * @mbggenerated
     */
    public BigDecimal getMonthOrderPay() {
        return monthOrderPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_passenger_statics.month_order_pay
     *
     * @param monthOrderPay the value for tbl_passenger_statics.month_order_pay
     *
     * @mbggenerated
     */
    public void setMonthOrderPay(BigDecimal monthOrderPay) {
        this.monthOrderPay = monthOrderPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_statics.total_invoice
     *
     * @return the value of tbl_passenger_statics.total_invoice
     *
     * @mbggenerated
     */
    public BigDecimal getTotalInvoice() {
        return totalInvoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_passenger_statics.total_invoice
     *
     * @param totalInvoice the value for tbl_passenger_statics.total_invoice
     *
     * @mbggenerated
     */
    public void setTotalInvoice(BigDecimal totalInvoice) {
        this.totalInvoice = totalInvoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_statics.can_invoice
     *
     * @return the value of tbl_passenger_statics.can_invoice
     *
     * @mbggenerated
     */
    public BigDecimal getCanInvoice() {
        return canInvoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_passenger_statics.can_invoice
     *
     * @param canInvoice the value for tbl_passenger_statics.can_invoice
     *
     * @mbggenerated
     */
    public void setCanInvoice(BigDecimal canInvoice) {
        this.canInvoice = canInvoice;
    }
}