package com.online.taxi.entity;

import java.util.Date;

public class SecretVoiceRecords {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_secret_voice_records.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_secret_voice_records.call_id
     *
     * @mbggenerated
     */
    private String callId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_secret_voice_records.subs_id
     *
     * @mbggenerated
     */
    private String subsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_secret_voice_records.call_time
     *
     * @mbggenerated
     */
    private Date callTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_secret_voice_records.flag
     *
     * @mbggenerated
     */
    private Integer flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_secret_voice_records.oss_download_url
     *
     * @mbggenerated
     */
    private String ossDownloadUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_secret_voice_records.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_secret_voice_records.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_secret_voice_records.id
     *
     * @return the value of tbl_secret_voice_records.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_secret_voice_records.id
     *
     * @param id the value for tbl_secret_voice_records.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_secret_voice_records.call_id
     *
     * @return the value of tbl_secret_voice_records.call_id
     *
     * @mbggenerated
     */
    public String getCallId() {
        return callId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_secret_voice_records.call_id
     *
     * @param callId the value for tbl_secret_voice_records.call_id
     *
     * @mbggenerated
     */
    public void setCallId(String callId) {
        this.callId = callId == null ? null : callId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_secret_voice_records.subs_id
     *
     * @return the value of tbl_secret_voice_records.subs_id
     *
     * @mbggenerated
     */
    public String getSubsId() {
        return subsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_secret_voice_records.subs_id
     *
     * @param subsId the value for tbl_secret_voice_records.subs_id
     *
     * @mbggenerated
     */
    public void setSubsId(String subsId) {
        this.subsId = subsId == null ? null : subsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_secret_voice_records.call_time
     *
     * @return the value of tbl_secret_voice_records.call_time
     *
     * @mbggenerated
     */
    public Date getCallTime() {
        return callTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_secret_voice_records.call_time
     *
     * @param callTime the value for tbl_secret_voice_records.call_time
     *
     * @mbggenerated
     */
    public void setCallTime(Date callTime) {
        this.callTime = callTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_secret_voice_records.flag
     *
     * @return the value of tbl_secret_voice_records.flag
     *
     * @mbggenerated
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_secret_voice_records.flag
     *
     * @param flag the value for tbl_secret_voice_records.flag
     *
     * @mbggenerated
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_secret_voice_records.oss_download_url
     *
     * @return the value of tbl_secret_voice_records.oss_download_url
     *
     * @mbggenerated
     */
    public String getOssDownloadUrl() {
        return ossDownloadUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_secret_voice_records.oss_download_url
     *
     * @param ossDownloadUrl the value for tbl_secret_voice_records.oss_download_url
     *
     * @mbggenerated
     */
    public void setOssDownloadUrl(String ossDownloadUrl) {
        this.ossDownloadUrl = ossDownloadUrl == null ? null : ossDownloadUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_secret_voice_records.create_time
     *
     * @return the value of tbl_secret_voice_records.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_secret_voice_records.create_time
     *
     * @param createTime the value for tbl_secret_voice_records.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_secret_voice_records.update_time
     *
     * @return the value of tbl_secret_voice_records.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_secret_voice_records.update_time
     *
     * @param updateTime the value for tbl_secret_voice_records.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}