package com.online.taxi.entity;

import java.util.Date;

public class ServiceType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_service_type.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_service_type.service_type_name
     *
     * @mbggenerated
     */
    private String serviceTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_service_type.service_type_status
     *
     * @mbggenerated
     */
    private Integer serviceTypeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_service_type.is_use
     *
     * @mbggenerated
     */
    private String isUse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_service_type.operator_id
     *
     * @mbggenerated
     */
    private Integer operatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_service_type.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_service_type.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_service_type.id
     *
     * @return the value of tbl_service_type.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_service_type.id
     *
     * @param id the value for tbl_service_type.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_service_type.service_type_name
     *
     * @return the value of tbl_service_type.service_type_name
     *
     * @mbggenerated
     */
    public String getServiceTypeName() {
        return serviceTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_service_type.service_type_name
     *
     * @param serviceTypeName the value for tbl_service_type.service_type_name
     *
     * @mbggenerated
     */
    public void setServiceTypeName(String serviceTypeName) {
        this.serviceTypeName = serviceTypeName == null ? null : serviceTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_service_type.service_type_status
     *
     * @return the value of tbl_service_type.service_type_status
     *
     * @mbggenerated
     */
    public Integer getServiceTypeStatus() {
        return serviceTypeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_service_type.service_type_status
     *
     * @param serviceTypeStatus the value for tbl_service_type.service_type_status
     *
     * @mbggenerated
     */
    public void setServiceTypeStatus(Integer serviceTypeStatus) {
        this.serviceTypeStatus = serviceTypeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_service_type.is_use
     *
     * @return the value of tbl_service_type.is_use
     *
     * @mbggenerated
     */
    public String getIsUse() {
        return isUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_service_type.is_use
     *
     * @param isUse the value for tbl_service_type.is_use
     *
     * @mbggenerated
     */
    public void setIsUse(String isUse) {
        this.isUse = isUse == null ? null : isUse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_service_type.operator_id
     *
     * @return the value of tbl_service_type.operator_id
     *
     * @mbggenerated
     */
    public Integer getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_service_type.operator_id
     *
     * @param operatorId the value for tbl_service_type.operator_id
     *
     * @mbggenerated
     */
    public void setOperatorId(Integer operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_service_type.create_time
     *
     * @return the value of tbl_service_type.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_service_type.create_time
     *
     * @param createTime the value for tbl_service_type.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_service_type.update_time
     *
     * @return the value of tbl_service_type.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_service_type.update_time
     *
     * @param updateTime the value for tbl_service_type.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}